[env:disco_h735ig]
platform = ststm32
board = disco_h735ig
framework = stm32cube
build_flags =
    -mfloat-abi=hard
    -mfpu=fpv4-sp-d16
    -D HSE_VALUE=25000000
board_build.ldscript = stm32h735ig_flash.ld
board_upload.offset_address = 0x08000000
extra_scripts = extra_script.py
