/* Automatically generated nanopb header */
/* Generated by nanopb-0.4.9.1 */

#ifndef PB_DC009_APL_COMM_DC009_APL_COMM_PB_H_INCLUDED
#define PB_DC009_APL_COMM_DC009_APL_COMM_PB_H_INCLUDED
#include <pb.h>

#if PB_PROTO_HEADER_VERSION != 40
#error Regenerate this file with the current version of nanopb generator.
#endif

/* Enum definitions */
typedef enum _dc009_apl_comm_SP_CHARGER_CHG_MODE {
    dc009_apl_comm_SP_CHARGER_CHG_MODE_SP_CHARGER_CHG_MODE_IDLE = 0,
    dc009_apl_comm_SP_CHARGER_CHG_MODE_SP_CHARGER_CHG_MODE_DRIVING_CHG = 1,
    dc009_apl_comm_SP_CHARGER_CHG_MODE_SP_CHARGER_CHG_MODE_BAT_MAINTENANCE = 2,
    dc009_apl_comm_SP_CHARGER_CHG_MODE_SP_CHARGER_CHG_MODE_PARKING_CHG = 3
} dc009_apl_comm_SP_CHARGER_CHG_MODE;

typedef enum _dc009_apl_comm_SP_CHARGER_DRIVING_CHG_SETTING {
    dc009_apl_comm_SP_CHARGER_DRIVING_CHG_SETTING_DRIVING_CHG_SETTING_IDLE = 0,
    dc009_apl_comm_SP_CHARGER_DRIVING_CHG_SETTING_DRIVING_CHG_SETTING_12V_IN_24V_OUT = 1,
    dc009_apl_comm_SP_CHARGER_DRIVING_CHG_SETTING_DRIVING_CHG_SETTING_12V_IN_48V_OUT = 2,
    dc009_apl_comm_SP_CHARGER_DRIVING_CHG_SETTING_DRIVING_CHG_SETTING_24V_IN_48V_OUT = 3
} dc009_apl_comm_SP_CHARGER_DRIVING_CHG_SETTING;

typedef enum _dc009_apl_comm_CAR_BATT_TYPE {
    dc009_apl_comm_CAR_BATT_TYPE_CAR_BATT_IDLE = 0,
    dc009_apl_comm_CAR_BATT_TYPE_CAR_BATT_12V_TYPE = 1,
    dc009_apl_comm_CAR_BATT_TYPE_CAR_BATT_24V_TYPE = 2
} dc009_apl_comm_CAR_BATT_TYPE;

typedef enum _dc009_apl_comm_DEV_BATT_CHG_XT60_SETTING {
    dc009_apl_comm_DEV_BATT_CHG_XT60_SETTING_DEV_BATT_CHG_XT60_IDLE = 0,
    dc009_apl_comm_DEV_BATT_CHG_XT60_SETTING_DEV_BATT_CHG_XT60_EF_DELTA_SERIES = 1,
    dc009_apl_comm_DEV_BATT_CHG_XT60_SETTING_DEV_BATT_CHG_XT60_EF_11V_TO_30V_SERIES = 2,
    dc009_apl_comm_DEV_BATT_CHG_XT60_SETTING_DEV_BATT_CHG_XT60_EF_11V_TO_60V_SERIES = 3,
    dc009_apl_comm_DEV_BATT_CHG_XT60_SETTING_DEV_BATT_CHG_XT60_OTHER_11V_TO_30V_SERIES = 4,
    dc009_apl_comm_DEV_BATT_CHG_XT60_SETTING_DEV_BATT_CHG_XT60_OTHER_11V_TO_60V_SERIES = 5
} dc009_apl_comm_DEV_BATT_CHG_XT60_SETTING;

/* Struct definitions */
typedef struct _dc009_apl_comm_EventPush {
    bool has_event_ver;
    uint32_t event_ver;
    bool has_event_seq;
    uint32_t event_seq;
    pb_callback_t event_item;
} dc009_apl_comm_EventPush;

typedef struct _dc009_apl_comm_EventPush_LogItem {
    bool has_unix_time;
    uint32_t unix_time;
    bool has_ms;
    uint32_t ms;
    bool has_event_no;
    uint32_t event_no;
    pb_callback_t event_detail;
} dc009_apl_comm_EventPush_LogItem;

typedef struct _dc009_apl_comm_EventAck {
    bool has_result;
    uint32_t result;
    bool has_event_seq;
    uint32_t event_seq;
    bool has_event_item_num;
    uint32_t event_item_num;
} dc009_apl_comm_EventAck;

typedef struct _dc009_apl_comm_PropertyUploadPeriod {
    bool has_display_property_full_upload_period;
    int32_t display_property_full_upload_period;
    bool has_display_property_incremental_upload_period;
    int32_t display_property_incremental_upload_period;
    bool has_runtime_property_full_upload_period;
    int32_t runtime_property_full_upload_period;
    bool has_runtime_property_incremental_upload_period;
    int32_t runtime_property_incremental_upload_period;
} dc009_apl_comm_PropertyUploadPeriod;

typedef struct _dc009_apl_comm_SpChargerDevBattChgXt60Setting {
    bool has_car_batt_type;
    dc009_apl_comm_CAR_BATT_TYPE car_batt_type;
    bool has_dev_batt_chg_xt60_setting;
    dc009_apl_comm_DEV_BATT_CHG_XT60_SETTING dev_batt_chg_xt60_setting;
} dc009_apl_comm_SpChargerDevBattChgXt60Setting;

typedef struct _dc009_apl_comm_ConfigWrite {
    bool has_cfg_power_off;
    bool cfg_power_off;
    bool has_cfg_power_on;
    bool cfg_power_on;
    bool has_reset_factory_setting;
    uint32_t reset_factory_setting;
    bool has_cfg_utc_time;
    uint32_t cfg_utc_time;
    bool has_cfg_utc_timezone;
    int32_t cfg_utc_timezone;
    bool has_cfg_display_property_full_upload_period;
    int32_t cfg_display_property_full_upload_period;
    bool has_cfg_display_property_incremental_upload_period;
    int32_t cfg_display_property_incremental_upload_period;
    bool has_cfg_runtime_property_full_upload_period;
    int32_t cfg_runtime_property_full_upload_period;
    bool has_cfg_runtime_property_incremental_upload_period;
    int32_t cfg_runtime_property_incremental_upload_period;
    bool has_active_display_property_full_upload;
    bool active_display_property_full_upload;
    bool has_active_runtime_property_full_upload;
    bool active_runtime_property_full_upload;
    bool has_cfg_sp_charger_chg_mode;
    dc009_apl_comm_SP_CHARGER_CHG_MODE cfg_sp_charger_chg_mode;
    bool has_cfg_sp_charger_chg_open;
    bool cfg_sp_charger_chg_open;
    bool has_cfg_sp_charger_chg_pow_limit;
    float cfg_sp_charger_chg_pow_limit;
    bool has_cfg_sp_charger_car_batt_vol_setting;
    uint32_t cfg_sp_charger_car_batt_vol_setting;
    bool has_cfg_sp_charger_extension_line_p_setting;
    float cfg_sp_charger_extension_line_p_setting;
    bool has_cfg_sp_charger_extension_line_n_setting;
    float cfg_sp_charger_extension_line_n_setting;
    bool has_cfg_sp_charger_driving_chg_setting;
    dc009_apl_comm_SP_CHARGER_DRIVING_CHG_SETTING cfg_sp_charger_driving_chg_setting;
    bool has_cfg_sp_charger_car_batt_chg_amp_limit;
    float cfg_sp_charger_car_batt_chg_amp_limit;
    bool has_cfg_sp_charger_dev_batt_chg_amp_limit;
    float cfg_sp_charger_dev_batt_chg_amp_limit;
    bool has_cfg_sp_charger_dev_batt_chg_xt60_setting;
    dc009_apl_comm_SpChargerDevBattChgXt60Setting cfg_sp_charger_dev_batt_chg_xt60_setting;
    bool has_cfg_sp_charger_car_batt_urgent_chg_switch;
    bool cfg_sp_charger_car_batt_urgent_chg_switch;
} dc009_apl_comm_ConfigWrite;

typedef struct _dc009_apl_comm_ConfigWriteAck {
    bool has_action_id;
    uint32_t action_id;
    bool has_config_ok;
    bool config_ok;
    bool has_cfg_power_off;
    bool cfg_power_off;
    bool has_cfg_power_on;
    bool cfg_power_on;
    bool has_reset_factory_setting;
    uint32_t reset_factory_setting;
    bool has_cfg_utc_time;
    uint32_t cfg_utc_time;
    bool has_cfg_utc_timezone;
    int32_t cfg_utc_timezone;
    bool has_cfg_display_property_full_upload_period;
    int32_t cfg_display_property_full_upload_period;
    bool has_cfg_display_property_incremental_upload_period;
    int32_t cfg_display_property_incremental_upload_period;
    bool has_cfg_runtime_property_full_upload_period;
    int32_t cfg_runtime_property_full_upload_period;
    bool has_cfg_runtime_property_incremental_upload_period;
    int32_t cfg_runtime_property_incremental_upload_period;
    bool has_active_display_property_full_upload;
    bool active_display_property_full_upload;
    bool has_active_runtime_property_full_upload;
    bool active_runtime_property_full_upload;
    bool has_cfg_sp_charger_chg_mode;
    dc009_apl_comm_SP_CHARGER_CHG_MODE cfg_sp_charger_chg_mode;
    bool has_cfg_sp_charger_chg_open;
    bool cfg_sp_charger_chg_open;
    bool has_cfg_sp_charger_chg_pow_limit;
    float cfg_sp_charger_chg_pow_limit;
    bool has_cfg_sp_charger_car_batt_vol_setting;
    uint32_t cfg_sp_charger_car_batt_vol_setting;
    bool has_cfg_sp_charger_extension_line_p_setting;
    float cfg_sp_charger_extension_line_p_setting;
    bool has_cfg_sp_charger_extension_line_n_setting;
    float cfg_sp_charger_extension_line_n_setting;
    bool has_cfg_sp_charger_driving_chg_setting;
    dc009_apl_comm_SP_CHARGER_DRIVING_CHG_SETTING cfg_sp_charger_driving_chg_setting;
    bool has_cfg_sp_charger_car_batt_chg_amp_limit;
    float cfg_sp_charger_car_batt_chg_amp_limit;
    bool has_cfg_sp_charger_dev_batt_chg_amp_limit;
    float cfg_sp_charger_dev_batt_chg_amp_limit;
    bool has_cfg_sp_charger_dev_batt_chg_xt60_setting;
    dc009_apl_comm_SpChargerDevBattChgXt60Setting cfg_sp_charger_dev_batt_chg_xt60_setting;
    bool has_cfg_sp_charger_car_batt_urgent_chg_switch;
    bool cfg_sp_charger_car_batt_urgent_chg_switch;
} dc009_apl_comm_ConfigWriteAck;

typedef struct _dc009_apl_comm_ConfigRead {
    pb_callback_t action_id;
} dc009_apl_comm_ConfigRead;

typedef struct _dc009_apl_comm_ConfigReadAck {
    bool has_cfg_utc_time;
    uint32_t cfg_utc_time;
    bool has_cfg_utc_timezone;
    int32_t cfg_utc_timezone;
} dc009_apl_comm_ConfigReadAck;

typedef struct _dc009_apl_comm_DisplayPropertyUpload {
    bool has_errcode;
    uint32_t errcode;
    bool has_pow_in_sum_w;
    float pow_in_sum_w;
    bool has_pow_out_sum_w;
    float pow_out_sum_w;
    bool has_cms_batt_temp;
    int32_t cms_batt_temp;
    bool has_pow_get_dc_bidi;
    float pow_get_dc_bidi;
    bool has_plug_in_info_dc_bidi_flag;
    bool plug_in_info_dc_bidi_flag;
    bool has_dev_online_flag;
    bool dev_online_flag;
    bool has_utc_timezone;
    int32_t utc_timezone;
    bool has_sp_charger_car_batt_vol_setting;
    uint32_t sp_charger_car_batt_vol_setting;
    bool has_sp_charger_car_batt_vol;
    float sp_charger_car_batt_vol;
    bool has_cms_batt_soc;
    float cms_batt_soc;
    bool has_cms_dsg_rem_time;
    uint32_t cms_dsg_rem_time;
    bool has_cms_chg_rem_time;
    uint32_t cms_chg_rem_time;
    bool has_cms_chg_dsg_state;
    uint32_t cms_chg_dsg_state;
    bool has_pow_get_dcp;
    float pow_get_dcp;
    bool has_plug_in_info_dcp_in_flag;
    bool plug_in_info_dcp_in_flag;
    bool has_plug_in_info_dcp_type;
    uint32_t plug_in_info_dcp_type;
    bool has_plug_in_info_dcp_detail;
    uint32_t plug_in_info_dcp_detail;
    pb_callback_t plug_in_info_dcp_sn;
    bool has_plug_in_info_dcp_run_state;
    uint32_t plug_in_info_dcp_run_state;
    bool has_sp_charger_chg_mode;
    dc009_apl_comm_SP_CHARGER_CHG_MODE sp_charger_chg_mode;
    bool has_sp_charger_run_state;
    uint32_t sp_charger_run_state;
    bool has_sp_charger_is_connect_car;
    bool sp_charger_is_connect_car;
    bool has_sp_charger_chg_open;
    bool sp_charger_chg_open;
    bool has_sp_charger_chg_pow_limit;
    float sp_charger_chg_pow_limit;
    bool has_module_bluetooth_snr;
    float module_bluetooth_snr;
    bool has_module_bluetooth_rssi;
    float module_bluetooth_rssi;
    bool has_module_wifi_snr;
    float module_wifi_snr;
    bool has_module_wifi_rssi;
    float module_wifi_rssi;
    bool has_sp_charger_chg_pow_max;
    float sp_charger_chg_pow_max;
    bool has_sp_charger_extension_line_p_setting;
    float sp_charger_extension_line_p_setting;
    bool has_sp_charger_extension_line_n_setting;
    float sp_charger_extension_line_n_setting;
    bool has_sp_charger_driving_chg_setting;
    dc009_apl_comm_SP_CHARGER_DRIVING_CHG_SETTING sp_charger_driving_chg_setting;
    bool has_sp_charger_car_batt_chg_amp_limit;
    float sp_charger_car_batt_chg_amp_limit;
    bool has_sp_charger_dev_batt_chg_amp_limit;
    float sp_charger_dev_batt_chg_amp_limit;
    bool has_sp_charger_dev_batt_chg_xt60_setting;
    dc009_apl_comm_SpChargerDevBattChgXt60Setting sp_charger_dev_batt_chg_xt60_setting;
    bool has_sp_charger_car_batt_chg_amp_max;
    float sp_charger_car_batt_chg_amp_max;
    bool has_sp_charger_car_batt_urgent_chg_state;
    uint32_t sp_charger_car_batt_urgent_chg_state;
    bool has_sp_charger_dev_batt_chg_amp_max;
    float sp_charger_dev_batt_chg_amp_max;
    bool has_sp_charger_car_batt_urgent_chg_switch;
    bool sp_charger_car_batt_urgent_chg_switch;
} dc009_apl_comm_DisplayPropertyUpload;

typedef struct _dc009_apl_comm_RuntimePropertyUpload {
    bool has_plug_in_info_dc_bidi_vol;
    float plug_in_info_dc_bidi_vol;
    bool has_plug_in_info_dc_bidi_amp;
    float plug_in_info_dc_bidi_amp;
    bool has_display_property_full_upload_period;
    int32_t display_property_full_upload_period;
    bool has_display_property_incremental_upload_period;
    int32_t display_property_incremental_upload_period;
    bool has_runtime_property_full_upload_period;
    int32_t runtime_property_full_upload_period;
    bool has_runtime_property_incremental_upload_period;
    int32_t runtime_property_incremental_upload_period;
    bool has_plug_in_info_dcp_vol;
    float plug_in_info_dcp_vol;
    bool has_plug_in_info_dcp_amp;
    float plug_in_info_dcp_amp;
} dc009_apl_comm_RuntimePropertyUpload;

typedef struct _dc009_apl_comm_DevRequest {
    bool has_dev_utc_time;
    uint32_t dev_utc_time;
    bool has_dev_utc_timezone;
    float dev_utc_timezone;
    bool has_require_property_upload_period;
    bool require_property_upload_period;
    bool has_require_time_service;
    bool require_time_service;
} dc009_apl_comm_DevRequest;

typedef struct _dc009_apl_comm_DevRequestAck {
    bool has_request_id;
    uint32_t request_id;
    bool has_require_ok;
    uint32_t require_ok;
    bool has_property_upload_period;
    dc009_apl_comm_PropertyUploadPeriod property_upload_period;
} dc009_apl_comm_DevRequestAck;


#ifdef __cplusplus
extern "C" {
#endif

/* Helper constants for enums */
#define _dc009_apl_comm_SP_CHARGER_CHG_MODE_MIN dc009_apl_comm_SP_CHARGER_CHG_MODE_SP_CHARGER_CHG_MODE_IDLE
#define _dc009_apl_comm_SP_CHARGER_CHG_MODE_MAX dc009_apl_comm_SP_CHARGER_CHG_MODE_SP_CHARGER_CHG_MODE_PARKING_CHG
#define _dc009_apl_comm_SP_CHARGER_CHG_MODE_ARRAYSIZE ((dc009_apl_comm_SP_CHARGER_CHG_MODE)(dc009_apl_comm_SP_CHARGER_CHG_MODE_SP_CHARGER_CHG_MODE_PARKING_CHG+1))

#define _dc009_apl_comm_SP_CHARGER_DRIVING_CHG_SETTING_MIN dc009_apl_comm_SP_CHARGER_DRIVING_CHG_SETTING_DRIVING_CHG_SETTING_IDLE
#define _dc009_apl_comm_SP_CHARGER_DRIVING_CHG_SETTING_MAX dc009_apl_comm_SP_CHARGER_DRIVING_CHG_SETTING_DRIVING_CHG_SETTING_24V_IN_48V_OUT
#define _dc009_apl_comm_SP_CHARGER_DRIVING_CHG_SETTING_ARRAYSIZE ((dc009_apl_comm_SP_CHARGER_DRIVING_CHG_SETTING)(dc009_apl_comm_SP_CHARGER_DRIVING_CHG_SETTING_DRIVING_CHG_SETTING_24V_IN_48V_OUT+1))

#define _dc009_apl_comm_CAR_BATT_TYPE_MIN dc009_apl_comm_CAR_BATT_TYPE_CAR_BATT_IDLE
#define _dc009_apl_comm_CAR_BATT_TYPE_MAX dc009_apl_comm_CAR_BATT_TYPE_CAR_BATT_24V_TYPE
#define _dc009_apl_comm_CAR_BATT_TYPE_ARRAYSIZE ((dc009_apl_comm_CAR_BATT_TYPE)(dc009_apl_comm_CAR_BATT_TYPE_CAR_BATT_24V_TYPE+1))

#define _dc009_apl_comm_DEV_BATT_CHG_XT60_SETTING_MIN dc009_apl_comm_DEV_BATT_CHG_XT60_SETTING_DEV_BATT_CHG_XT60_IDLE
#define _dc009_apl_comm_DEV_BATT_CHG_XT60_SETTING_MAX dc009_apl_comm_DEV_BATT_CHG_XT60_SETTING_DEV_BATT_CHG_XT60_OTHER_11V_TO_60V_SERIES
#define _dc009_apl_comm_DEV_BATT_CHG_XT60_SETTING_ARRAYSIZE ((dc009_apl_comm_DEV_BATT_CHG_XT60_SETTING)(dc009_apl_comm_DEV_BATT_CHG_XT60_SETTING_DEV_BATT_CHG_XT60_OTHER_11V_TO_60V_SERIES+1))





#define dc009_apl_comm_SpChargerDevBattChgXt60Setting_car_batt_type_ENUMTYPE dc009_apl_comm_CAR_BATT_TYPE
#define dc009_apl_comm_SpChargerDevBattChgXt60Setting_dev_batt_chg_xt60_setting_ENUMTYPE dc009_apl_comm_DEV_BATT_CHG_XT60_SETTING

#define dc009_apl_comm_ConfigWrite_cfg_sp_charger_chg_mode_ENUMTYPE dc009_apl_comm_SP_CHARGER_CHG_MODE
#define dc009_apl_comm_ConfigWrite_cfg_sp_charger_driving_chg_setting_ENUMTYPE dc009_apl_comm_SP_CHARGER_DRIVING_CHG_SETTING

#define dc009_apl_comm_ConfigWriteAck_cfg_sp_charger_chg_mode_ENUMTYPE dc009_apl_comm_SP_CHARGER_CHG_MODE
#define dc009_apl_comm_ConfigWriteAck_cfg_sp_charger_driving_chg_setting_ENUMTYPE dc009_apl_comm_SP_CHARGER_DRIVING_CHG_SETTING



#define dc009_apl_comm_DisplayPropertyUpload_sp_charger_chg_mode_ENUMTYPE dc009_apl_comm_SP_CHARGER_CHG_MODE
#define dc009_apl_comm_DisplayPropertyUpload_sp_charger_driving_chg_setting_ENUMTYPE dc009_apl_comm_SP_CHARGER_DRIVING_CHG_SETTING





/* Initializer values for message structs */
#define dc009_apl_comm_EventPush_init_default    {false, 0, false, 0, {{NULL}, NULL}}
#define dc009_apl_comm_EventPush_LogItem_init_default {false, 0, false, 0, false, 0, {{NULL}, NULL}}
#define dc009_apl_comm_EventAck_init_default     {false, 0, false, 0, false, 0}
#define dc009_apl_comm_PropertyUploadPeriod_init_default {false, 0, false, 0, false, 0, false, 0}
#define dc009_apl_comm_SpChargerDevBattChgXt60Setting_init_default {false, _dc009_apl_comm_CAR_BATT_TYPE_MIN, false, _dc009_apl_comm_DEV_BATT_CHG_XT60_SETTING_MIN}
#define dc009_apl_comm_ConfigWrite_init_default  {false, 0, false, 0, false, 0, false, 0, false, 0, false, 0, false, 0, false, 0, false, 0, false, 0, false, 0, false, _dc009_apl_comm_SP_CHARGER_CHG_MODE_MIN, false, 0, false, 0, false, 0, false, 0, false, 0, false, _dc009_apl_comm_SP_CHARGER_DRIVING_CHG_SETTING_MIN, false, 0, false, 0, false, dc009_apl_comm_SpChargerDevBattChgXt60Setting_init_default, false, 0}
#define dc009_apl_comm_ConfigWriteAck_init_default {false, 0, false, 0, false, 0, false, 0, false, 0, false, 0, false, 0, false, 0, false, 0, false, 0, false, 0, false, 0, false, 0, false, _dc009_apl_comm_SP_CHARGER_CHG_MODE_MIN, false, 0, false, 0, false, 0, false, 0, false, 0, false, _dc009_apl_comm_SP_CHARGER_DRIVING_CHG_SETTING_MIN, false, 0, false, 0, false, dc009_apl_comm_SpChargerDevBattChgXt60Setting_init_default, false, 0}
#define dc009_apl_comm_ConfigRead_init_default   {{{NULL}, NULL}}
#define dc009_apl_comm_ConfigReadAck_init_default {false, 0, false, 0}
#define dc009_apl_comm_DisplayPropertyUpload_init_default {false, 0, false, 0, false, 0, false, 0, false, 0, false, 0, false, 0, false, 0, false, 0, false, 0, false, 0, false, 0, false, 0, false, 0, false, 0, false, 0, false, 0, false, 0, {{NULL}, NULL}, false, 0, false, _dc009_apl_comm_SP_CHARGER_CHG_MODE_MIN, false, 0, false, 0, false, 0, false, 0, false, 0, false, 0, false, 0, false, 0, false, 0, false, 0, false, 0, false, _dc009_apl_comm_SP_CHARGER_DRIVING_CHG_SETTING_MIN, false, 0, false, 0, false, dc009_apl_comm_SpChargerDevBattChgXt60Setting_init_default, false, 0, false, 0, false, 0, false, 0}
#define dc009_apl_comm_RuntimePropertyUpload_init_default {false, 0, false, 0, false, 0, false, 0, false, 0, false, 0, false, 0, false, 0}
#define dc009_apl_comm_DevRequest_init_default   {false, 0, false, 0, false, 0, false, 0}
#define dc009_apl_comm_DevRequestAck_init_default {false, 0, false, 0, false, dc009_apl_comm_PropertyUploadPeriod_init_default}
#define dc009_apl_comm_EventPush_init_zero       {false, 0, false, 0, {{NULL}, NULL}}
#define dc009_apl_comm_EventPush_LogItem_init_zero {false, 0, false, 0, false, 0, {{NULL}, NULL}}
#define dc009_apl_comm_EventAck_init_zero        {false, 0, false, 0, false, 0}
#define dc009_apl_comm_PropertyUploadPeriod_init_zero {false, 0, false, 0, false, 0, false, 0}
#define dc009_apl_comm_SpChargerDevBattChgXt60Setting_init_zero {false, _dc009_apl_comm_CAR_BATT_TYPE_MIN, false, _dc009_apl_comm_DEV_BATT_CHG_XT60_SETTING_MIN}
#define dc009_apl_comm_ConfigWrite_init_zero     {false, 0, false, 0, false, 0, false, 0, false, 0, false, 0, false, 0, false, 0, false, 0, false, 0, false, 0, false, _dc009_apl_comm_SP_CHARGER_CHG_MODE_MIN, false, 0, false, 0, false, 0, false, 0, false, 0, false, _dc009_apl_comm_SP_CHARGER_DRIVING_CHG_SETTING_MIN, false, 0, false, 0, false, dc009_apl_comm_SpChargerDevBattChgXt60Setting_init_zero, false, 0}
#define dc009_apl_comm_ConfigWriteAck_init_zero  {false, 0, false, 0, false, 0, false, 0, false, 0, false, 0, false, 0, false, 0, false, 0, false, 0, false, 0, false, 0, false, 0, false, _dc009_apl_comm_SP_CHARGER_CHG_MODE_MIN, false, 0, false, 0, false, 0, false, 0, false, 0, false, _dc009_apl_comm_SP_CHARGER_DRIVING_CHG_SETTING_MIN, false, 0, false, 0, false, dc009_apl_comm_SpChargerDevBattChgXt60Setting_init_zero, false, 0}
#define dc009_apl_comm_ConfigRead_init_zero      {{{NULL}, NULL}}
#define dc009_apl_comm_ConfigReadAck_init_zero   {false, 0, false, 0}
#define dc009_apl_comm_DisplayPropertyUpload_init_zero {false, 0, false, 0, false, 0, false, 0, false, 0, false, 0, false, 0, false, 0, false, 0, false, 0, false, 0, false, 0, false, 0, false, 0, false, 0, false, 0, false, 0, false, 0, {{NULL}, NULL}, false, 0, false, _dc009_apl_comm_SP_CHARGER_CHG_MODE_MIN, false, 0, false, 0, false, 0, false, 0, false, 0, false, 0, false, 0, false, 0, false, 0, false, 0, false, 0, false, _dc009_apl_comm_SP_CHARGER_DRIVING_CHG_SETTING_MIN, false, 0, false, 0, false, dc009_apl_comm_SpChargerDevBattChgXt60Setting_init_zero, false, 0, false, 0, false, 0, false, 0}
#define dc009_apl_comm_RuntimePropertyUpload_init_zero {false, 0, false, 0, false, 0, false, 0, false, 0, false, 0, false, 0, false, 0}
#define dc009_apl_comm_DevRequest_init_zero      {false, 0, false, 0, false, 0, false, 0}
#define dc009_apl_comm_DevRequestAck_init_zero   {false, 0, false, 0, false, dc009_apl_comm_PropertyUploadPeriod_init_zero}

/* Field tags (for use in manual encoding/decoding) */
#define dc009_apl_comm_EventPush_event_ver_tag   1
#define dc009_apl_comm_EventPush_event_seq_tag   2
#define dc009_apl_comm_EventPush_event_item_tag  3
#define dc009_apl_comm_EventPush_LogItem_unix_time_tag 1
#define dc009_apl_comm_EventPush_LogItem_ms_tag  2
#define dc009_apl_comm_EventPush_LogItem_event_no_tag 3
#define dc009_apl_comm_EventPush_LogItem_event_detail_tag 4
#define dc009_apl_comm_EventAck_result_tag       1
#define dc009_apl_comm_EventAck_event_seq_tag    2
#define dc009_apl_comm_EventAck_event_item_num_tag 3
#define dc009_apl_comm_PropertyUploadPeriod_display_property_full_upload_period_tag 1
#define dc009_apl_comm_PropertyUploadPeriod_display_property_incremental_upload_period_tag 2
#define dc009_apl_comm_PropertyUploadPeriod_runtime_property_full_upload_period_tag 3
#define dc009_apl_comm_PropertyUploadPeriod_runtime_property_incremental_upload_period_tag 4
#define dc009_apl_comm_SpChargerDevBattChgXt60Setting_car_batt_type_tag 1
#define dc009_apl_comm_SpChargerDevBattChgXt60Setting_dev_batt_chg_xt60_setting_tag 2
#define dc009_apl_comm_ConfigWrite_cfg_power_off_tag 3
#define dc009_apl_comm_ConfigWrite_cfg_power_on_tag 4
#define dc009_apl_comm_ConfigWrite_reset_factory_setting_tag 5
#define dc009_apl_comm_ConfigWrite_cfg_utc_time_tag 6
#define dc009_apl_comm_ConfigWrite_cfg_utc_timezone_tag 7
#define dc009_apl_comm_ConfigWrite_cfg_display_property_full_upload_period_tag 67
#define dc009_apl_comm_ConfigWrite_cfg_display_property_incremental_upload_period_tag 68
#define dc009_apl_comm_ConfigWrite_cfg_runtime_property_full_upload_period_tag 69
#define dc009_apl_comm_ConfigWrite_cfg_runtime_property_incremental_upload_period_tag 70
#define dc009_apl_comm_ConfigWrite_active_display_property_full_upload_tag 71
#define dc009_apl_comm_ConfigWrite_active_runtime_property_full_upload_tag 72
#define dc009_apl_comm_ConfigWrite_cfg_sp_charger_chg_mode_tag 116
#define dc009_apl_comm_ConfigWrite_cfg_sp_charger_chg_open_tag 122
#define dc009_apl_comm_ConfigWrite_cfg_sp_charger_chg_pow_limit_tag 123
#define dc009_apl_comm_ConfigWrite_cfg_sp_charger_car_batt_vol_setting_tag 137
#define dc009_apl_comm_ConfigWrite_cfg_sp_charger_extension_line_p_setting_tag 203
#define dc009_apl_comm_ConfigWrite_cfg_sp_charger_extension_line_n_setting_tag 204
#define dc009_apl_comm_ConfigWrite_cfg_sp_charger_driving_chg_setting_tag 205
#define dc009_apl_comm_ConfigWrite_cfg_sp_charger_car_batt_chg_amp_limit_tag 217
#define dc009_apl_comm_ConfigWrite_cfg_sp_charger_dev_batt_chg_amp_limit_tag 218
#define dc009_apl_comm_ConfigWrite_cfg_sp_charger_dev_batt_chg_xt60_setting_tag 219
#define dc009_apl_comm_ConfigWrite_cfg_sp_charger_car_batt_urgent_chg_switch_tag 221
#define dc009_apl_comm_ConfigWriteAck_action_id_tag 1
#define dc009_apl_comm_ConfigWriteAck_config_ok_tag 2
#define dc009_apl_comm_ConfigWriteAck_cfg_power_off_tag 3
#define dc009_apl_comm_ConfigWriteAck_cfg_power_on_tag 4
#define dc009_apl_comm_ConfigWriteAck_reset_factory_setting_tag 5
#define dc009_apl_comm_ConfigWriteAck_cfg_utc_time_tag 6
#define dc009_apl_comm_ConfigWriteAck_cfg_utc_timezone_tag 7
#define dc009_apl_comm_ConfigWriteAck_cfg_display_property_full_upload_period_tag 67
#define dc009_apl_comm_ConfigWriteAck_cfg_display_property_incremental_upload_period_tag 68
#define dc009_apl_comm_ConfigWriteAck_cfg_runtime_property_full_upload_period_tag 69
#define dc009_apl_comm_ConfigWriteAck_cfg_runtime_property_incremental_upload_period_tag 70
#define dc009_apl_comm_ConfigWriteAck_active_display_property_full_upload_tag 71
#define dc009_apl_comm_ConfigWriteAck_active_runtime_property_full_upload_tag 72
#define dc009_apl_comm_ConfigWriteAck_cfg_sp_charger_chg_mode_tag 116
#define dc009_apl_comm_ConfigWriteAck_cfg_sp_charger_chg_open_tag 122
#define dc009_apl_comm_ConfigWriteAck_cfg_sp_charger_chg_pow_limit_tag 123
#define dc009_apl_comm_ConfigWriteAck_cfg_sp_charger_car_batt_vol_setting_tag 137
#define dc009_apl_comm_ConfigWriteAck_cfg_sp_charger_extension_line_p_setting_tag 203
#define dc009_apl_comm_ConfigWriteAck_cfg_sp_charger_extension_line_n_setting_tag 204
#define dc009_apl_comm_ConfigWriteAck_cfg_sp_charger_driving_chg_setting_tag 205
#define dc009_apl_comm_ConfigWriteAck_cfg_sp_charger_car_batt_chg_amp_limit_tag 217
#define dc009_apl_comm_ConfigWriteAck_cfg_sp_charger_dev_batt_chg_amp_limit_tag 218
#define dc009_apl_comm_ConfigWriteAck_cfg_sp_charger_dev_batt_chg_xt60_setting_tag 219
#define dc009_apl_comm_ConfigWriteAck_cfg_sp_charger_car_batt_urgent_chg_switch_tag 221
#define dc009_apl_comm_ConfigRead_action_id_tag  1
#define dc009_apl_comm_ConfigReadAck_cfg_utc_time_tag 6
#define dc009_apl_comm_ConfigReadAck_cfg_utc_timezone_tag 7
#define dc009_apl_comm_DisplayPropertyUpload_errcode_tag 1
#define dc009_apl_comm_DisplayPropertyUpload_pow_in_sum_w_tag 3
#define dc009_apl_comm_DisplayPropertyUpload_pow_out_sum_w_tag 4
#define dc009_apl_comm_DisplayPropertyUpload_cms_batt_temp_tag 102
#define dc009_apl_comm_DisplayPropertyUpload_pow_get_dc_bidi_tag 105
#define dc009_apl_comm_DisplayPropertyUpload_plug_in_info_dc_bidi_flag_tag 106
#define dc009_apl_comm_DisplayPropertyUpload_dev_online_flag_tag 130
#define dc009_apl_comm_DisplayPropertyUpload_utc_timezone_tag 133
#define dc009_apl_comm_DisplayPropertyUpload_sp_charger_car_batt_vol_setting_tag 138
#define dc009_apl_comm_DisplayPropertyUpload_sp_charger_car_batt_vol_tag 139
#define dc009_apl_comm_DisplayPropertyUpload_cms_batt_soc_tag 262
#define dc009_apl_comm_DisplayPropertyUpload_cms_dsg_rem_time_tag 268
#define dc009_apl_comm_DisplayPropertyUpload_cms_chg_rem_time_tag 269
#define dc009_apl_comm_DisplayPropertyUpload_cms_chg_dsg_state_tag 282
#define dc009_apl_comm_DisplayPropertyUpload_pow_get_dcp_tag 425
#define dc009_apl_comm_DisplayPropertyUpload_plug_in_info_dcp_in_flag_tag 426
#define dc009_apl_comm_DisplayPropertyUpload_plug_in_info_dcp_type_tag 427
#define dc009_apl_comm_DisplayPropertyUpload_plug_in_info_dcp_detail_tag 428
#define dc009_apl_comm_DisplayPropertyUpload_plug_in_info_dcp_sn_tag 433
#define dc009_apl_comm_DisplayPropertyUpload_plug_in_info_dcp_run_state_tag 436
#define dc009_apl_comm_DisplayPropertyUpload_sp_charger_chg_mode_tag 581
#define dc009_apl_comm_DisplayPropertyUpload_sp_charger_run_state_tag 582
#define dc009_apl_comm_DisplayPropertyUpload_sp_charger_is_connect_car_tag 583
#define dc009_apl_comm_DisplayPropertyUpload_sp_charger_chg_open_tag 597
#define dc009_apl_comm_DisplayPropertyUpload_sp_charger_chg_pow_limit_tag 598
#define dc009_apl_comm_DisplayPropertyUpload_module_bluetooth_snr_tag 599
#define dc009_apl_comm_DisplayPropertyUpload_module_bluetooth_rssi_tag 600
#define dc009_apl_comm_DisplayPropertyUpload_module_wifi_snr_tag 601
#define dc009_apl_comm_DisplayPropertyUpload_module_wifi_rssi_tag 602
#define dc009_apl_comm_DisplayPropertyUpload_sp_charger_chg_pow_max_tag 603
#define dc009_apl_comm_DisplayPropertyUpload_sp_charger_extension_line_p_setting_tag 608
#define dc009_apl_comm_DisplayPropertyUpload_sp_charger_extension_line_n_setting_tag 609
#define dc009_apl_comm_DisplayPropertyUpload_sp_charger_driving_chg_setting_tag 610
#define dc009_apl_comm_DisplayPropertyUpload_sp_charger_car_batt_chg_amp_limit_tag 624
#define dc009_apl_comm_DisplayPropertyUpload_sp_charger_dev_batt_chg_amp_limit_tag 625
#define dc009_apl_comm_DisplayPropertyUpload_sp_charger_dev_batt_chg_xt60_setting_tag 626
#define dc009_apl_comm_DisplayPropertyUpload_sp_charger_car_batt_chg_amp_max_tag 723
#define dc009_apl_comm_DisplayPropertyUpload_sp_charger_car_batt_urgent_chg_state_tag 724
#define dc009_apl_comm_DisplayPropertyUpload_sp_charger_dev_batt_chg_amp_max_tag 725
#define dc009_apl_comm_DisplayPropertyUpload_sp_charger_car_batt_urgent_chg_switch_tag 726
#define dc009_apl_comm_RuntimePropertyUpload_plug_in_info_dc_bidi_vol_tag 103
#define dc009_apl_comm_RuntimePropertyUpload_plug_in_info_dc_bidi_amp_tag 104
#define dc009_apl_comm_RuntimePropertyUpload_display_property_full_upload_period_tag 293
#define dc009_apl_comm_RuntimePropertyUpload_display_property_incremental_upload_period_tag 294
#define dc009_apl_comm_RuntimePropertyUpload_runtime_property_full_upload_period_tag 295
#define dc009_apl_comm_RuntimePropertyUpload_runtime_property_incremental_upload_period_tag 296
#define dc009_apl_comm_RuntimePropertyUpload_plug_in_info_dcp_vol_tag 443
#define dc009_apl_comm_RuntimePropertyUpload_plug_in_info_dcp_amp_tag 448
#define dc009_apl_comm_DevRequest_dev_utc_time_tag 1
#define dc009_apl_comm_DevRequest_dev_utc_timezone_tag 2
#define dc009_apl_comm_DevRequest_require_property_upload_period_tag 3
#define dc009_apl_comm_DevRequest_require_time_service_tag 5
#define dc009_apl_comm_DevRequestAck_request_id_tag 1
#define dc009_apl_comm_DevRequestAck_require_ok_tag 2
#define dc009_apl_comm_DevRequestAck_property_upload_period_tag 3

/* Struct field encoding specification for nanopb */
#define dc009_apl_comm_EventPush_FIELDLIST(X, a) \
X(a, STATIC,   OPTIONAL, UINT32,   event_ver,         1) \
X(a, STATIC,   OPTIONAL, UINT32,   event_seq,         2) \
X(a, CALLBACK, REPEATED, MESSAGE,  event_item,        3)
#define dc009_apl_comm_EventPush_CALLBACK pb_default_field_callback
#define dc009_apl_comm_EventPush_DEFAULT NULL
#define dc009_apl_comm_EventPush_event_item_MSGTYPE dc009_apl_comm_EventPush_LogItem

#define dc009_apl_comm_EventPush_LogItem_FIELDLIST(X, a) \
X(a, STATIC,   OPTIONAL, UINT32,   unix_time,         1) \
X(a, STATIC,   OPTIONAL, UINT32,   ms,                2) \
X(a, STATIC,   OPTIONAL, UINT32,   event_no,          3) \
X(a, CALLBACK, REPEATED, FLOAT,    event_detail,      4)
#define dc009_apl_comm_EventPush_LogItem_CALLBACK pb_default_field_callback
#define dc009_apl_comm_EventPush_LogItem_DEFAULT NULL

#define dc009_apl_comm_EventAck_FIELDLIST(X, a) \
X(a, STATIC,   OPTIONAL, UINT32,   result,            1) \
X(a, STATIC,   OPTIONAL, UINT32,   event_seq,         2) \
X(a, STATIC,   OPTIONAL, UINT32,   event_item_num,    3)
#define dc009_apl_comm_EventAck_CALLBACK NULL
#define dc009_apl_comm_EventAck_DEFAULT NULL

#define dc009_apl_comm_PropertyUploadPeriod_FIELDLIST(X, a) \
X(a, STATIC,   OPTIONAL, INT32,    display_property_full_upload_period,   1) \
X(a, STATIC,   OPTIONAL, INT32,    display_property_incremental_upload_period,   2) \
X(a, STATIC,   OPTIONAL, INT32,    runtime_property_full_upload_period,   3) \
X(a, STATIC,   OPTIONAL, INT32,    runtime_property_incremental_upload_period,   4)
#define dc009_apl_comm_PropertyUploadPeriod_CALLBACK NULL
#define dc009_apl_comm_PropertyUploadPeriod_DEFAULT NULL

#define dc009_apl_comm_SpChargerDevBattChgXt60Setting_FIELDLIST(X, a) \
X(a, STATIC,   OPTIONAL, UENUM,    car_batt_type,     1) \
X(a, STATIC,   OPTIONAL, UENUM,    dev_batt_chg_xt60_setting,   2)
#define dc009_apl_comm_SpChargerDevBattChgXt60Setting_CALLBACK NULL
#define dc009_apl_comm_SpChargerDevBattChgXt60Setting_DEFAULT NULL

#define dc009_apl_comm_ConfigWrite_FIELDLIST(X, a) \
X(a, STATIC,   OPTIONAL, BOOL,     cfg_power_off,     3) \
X(a, STATIC,   OPTIONAL, BOOL,     cfg_power_on,      4) \
X(a, STATIC,   OPTIONAL, UINT32,   reset_factory_setting,   5) \
X(a, STATIC,   OPTIONAL, UINT32,   cfg_utc_time,      6) \
X(a, STATIC,   OPTIONAL, INT32,    cfg_utc_timezone,   7) \
X(a, STATIC,   OPTIONAL, INT32,    cfg_display_property_full_upload_period,  67) \
X(a, STATIC,   OPTIONAL, INT32,    cfg_display_property_incremental_upload_period,  68) \
X(a, STATIC,   OPTIONAL, INT32,    cfg_runtime_property_full_upload_period,  69) \
X(a, STATIC,   OPTIONAL, INT32,    cfg_runtime_property_incremental_upload_period,  70) \
X(a, STATIC,   OPTIONAL, BOOL,     active_display_property_full_upload,  71) \
X(a, STATIC,   OPTIONAL, BOOL,     active_runtime_property_full_upload,  72) \
X(a, STATIC,   OPTIONAL, UENUM,    cfg_sp_charger_chg_mode, 116) \
X(a, STATIC,   OPTIONAL, BOOL,     cfg_sp_charger_chg_open, 122) \
X(a, STATIC,   OPTIONAL, FLOAT,    cfg_sp_charger_chg_pow_limit, 123) \
X(a, STATIC,   OPTIONAL, UINT32,   cfg_sp_charger_car_batt_vol_setting, 137) \
X(a, STATIC,   OPTIONAL, FLOAT,    cfg_sp_charger_extension_line_p_setting, 203) \
X(a, STATIC,   OPTIONAL, FLOAT,    cfg_sp_charger_extension_line_n_setting, 204) \
X(a, STATIC,   OPTIONAL, UENUM,    cfg_sp_charger_driving_chg_setting, 205) \
X(a, STATIC,   OPTIONAL, FLOAT,    cfg_sp_charger_car_batt_chg_amp_limit, 217) \
X(a, STATIC,   OPTIONAL, FLOAT,    cfg_sp_charger_dev_batt_chg_amp_limit, 218) \
X(a, STATIC,   OPTIONAL, MESSAGE,  cfg_sp_charger_dev_batt_chg_xt60_setting, 219) \
X(a, STATIC,   OPTIONAL, BOOL,     cfg_sp_charger_car_batt_urgent_chg_switch, 221)
#define dc009_apl_comm_ConfigWrite_CALLBACK NULL
#define dc009_apl_comm_ConfigWrite_DEFAULT NULL
#define dc009_apl_comm_ConfigWrite_cfg_sp_charger_dev_batt_chg_xt60_setting_MSGTYPE dc009_apl_comm_SpChargerDevBattChgXt60Setting

#define dc009_apl_comm_ConfigWriteAck_FIELDLIST(X, a) \
X(a, STATIC,   OPTIONAL, UINT32,   action_id,         1) \
X(a, STATIC,   OPTIONAL, BOOL,     config_ok,         2) \
X(a, STATIC,   OPTIONAL, BOOL,     cfg_power_off,     3) \
X(a, STATIC,   OPTIONAL, BOOL,     cfg_power_on,      4) \
X(a, STATIC,   OPTIONAL, UINT32,   reset_factory_setting,   5) \
X(a, STATIC,   OPTIONAL, UINT32,   cfg_utc_time,      6) \
X(a, STATIC,   OPTIONAL, INT32,    cfg_utc_timezone,   7) \
X(a, STATIC,   OPTIONAL, INT32,    cfg_display_property_full_upload_period,  67) \
X(a, STATIC,   OPTIONAL, INT32,    cfg_display_property_incremental_upload_period,  68) \
X(a, STATIC,   OPTIONAL, INT32,    cfg_runtime_property_full_upload_period,  69) \
X(a, STATIC,   OPTIONAL, INT32,    cfg_runtime_property_incremental_upload_period,  70) \
X(a, STATIC,   OPTIONAL, BOOL,     active_display_property_full_upload,  71) \
X(a, STATIC,   OPTIONAL, BOOL,     active_runtime_property_full_upload,  72) \
X(a, STATIC,   OPTIONAL, UENUM,    cfg_sp_charger_chg_mode, 116) \
X(a, STATIC,   OPTIONAL, BOOL,     cfg_sp_charger_chg_open, 122) \
X(a, STATIC,   OPTIONAL, FLOAT,    cfg_sp_charger_chg_pow_limit, 123) \
X(a, STATIC,   OPTIONAL, UINT32,   cfg_sp_charger_car_batt_vol_setting, 137) \
X(a, STATIC,   OPTIONAL, FLOAT,    cfg_sp_charger_extension_line_p_setting, 203) \
X(a, STATIC,   OPTIONAL, FLOAT,    cfg_sp_charger_extension_line_n_setting, 204) \
X(a, STATIC,   OPTIONAL, UENUM,    cfg_sp_charger_driving_chg_setting, 205) \
X(a, STATIC,   OPTIONAL, FLOAT,    cfg_sp_charger_car_batt_chg_amp_limit, 217) \
X(a, STATIC,   OPTIONAL, FLOAT,    cfg_sp_charger_dev_batt_chg_amp_limit, 218) \
X(a, STATIC,   OPTIONAL, MESSAGE,  cfg_sp_charger_dev_batt_chg_xt60_setting, 219) \
X(a, STATIC,   OPTIONAL, BOOL,     cfg_sp_charger_car_batt_urgent_chg_switch, 221)
#define dc009_apl_comm_ConfigWriteAck_CALLBACK NULL
#define dc009_apl_comm_ConfigWriteAck_DEFAULT NULL
#define dc009_apl_comm_ConfigWriteAck_cfg_sp_charger_dev_batt_chg_xt60_setting_MSGTYPE dc009_apl_comm_SpChargerDevBattChgXt60Setting

#define dc009_apl_comm_ConfigRead_FIELDLIST(X, a) \
X(a, CALLBACK, REPEATED, UINT32,   action_id,         1)
#define dc009_apl_comm_ConfigRead_CALLBACK pb_default_field_callback
#define dc009_apl_comm_ConfigRead_DEFAULT NULL

#define dc009_apl_comm_ConfigReadAck_FIELDLIST(X, a) \
X(a, STATIC,   OPTIONAL, UINT32,   cfg_utc_time,      6) \
X(a, STATIC,   OPTIONAL, INT32,    cfg_utc_timezone,   7)
#define dc009_apl_comm_ConfigReadAck_CALLBACK NULL
#define dc009_apl_comm_ConfigReadAck_DEFAULT NULL

#define dc009_apl_comm_DisplayPropertyUpload_FIELDLIST(X, a) \
X(a, STATIC,   OPTIONAL, UINT32,   errcode,           1) \
X(a, STATIC,   OPTIONAL, FLOAT,    pow_in_sum_w,      3) \
X(a, STATIC,   OPTIONAL, FLOAT,    pow_out_sum_w,     4) \
X(a, STATIC,   OPTIONAL, INT32,    cms_batt_temp,   102) \
X(a, STATIC,   OPTIONAL, FLOAT,    pow_get_dc_bidi, 105) \
X(a, STATIC,   OPTIONAL, BOOL,     plug_in_info_dc_bidi_flag, 106) \
X(a, STATIC,   OPTIONAL, BOOL,     dev_online_flag, 130) \
X(a, STATIC,   OPTIONAL, INT32,    utc_timezone,    133) \
X(a, STATIC,   OPTIONAL, UINT32,   sp_charger_car_batt_vol_setting, 138) \
X(a, STATIC,   OPTIONAL, FLOAT,    sp_charger_car_batt_vol, 139) \
X(a, STATIC,   OPTIONAL, FLOAT,    cms_batt_soc,    262) \
X(a, STATIC,   OPTIONAL, UINT32,   cms_dsg_rem_time, 268) \
X(a, STATIC,   OPTIONAL, UINT32,   cms_chg_rem_time, 269) \
X(a, STATIC,   OPTIONAL, UINT32,   cms_chg_dsg_state, 282) \
X(a, STATIC,   OPTIONAL, FLOAT,    pow_get_dcp,     425) \
X(a, STATIC,   OPTIONAL, BOOL,     plug_in_info_dcp_in_flag, 426) \
X(a, STATIC,   OPTIONAL, UINT32,   plug_in_info_dcp_type, 427) \
X(a, STATIC,   OPTIONAL, UINT32,   plug_in_info_dcp_detail, 428) \
X(a, CALLBACK, OPTIONAL, STRING,   plug_in_info_dcp_sn, 433) \
X(a, STATIC,   OPTIONAL, UINT32,   plug_in_info_dcp_run_state, 436) \
X(a, STATIC,   OPTIONAL, UENUM,    sp_charger_chg_mode, 581) \
X(a, STATIC,   OPTIONAL, UINT32,   sp_charger_run_state, 582) \
X(a, STATIC,   OPTIONAL, BOOL,     sp_charger_is_connect_car, 583) \
X(a, STATIC,   OPTIONAL, BOOL,     sp_charger_chg_open, 597) \
X(a, STATIC,   OPTIONAL, FLOAT,    sp_charger_chg_pow_limit, 598) \
X(a, STATIC,   OPTIONAL, FLOAT,    module_bluetooth_snr, 599) \
X(a, STATIC,   OPTIONAL, FLOAT,    module_bluetooth_rssi, 600) \
X(a, STATIC,   OPTIONAL, FLOAT,    module_wifi_snr, 601) \
X(a, STATIC,   OPTIONAL, FLOAT,    module_wifi_rssi, 602) \
X(a, STATIC,   OPTIONAL, FLOAT,    sp_charger_chg_pow_max, 603) \
X(a, STATIC,   OPTIONAL, FLOAT,    sp_charger_extension_line_p_setting, 608) \
X(a, STATIC,   OPTIONAL, FLOAT,    sp_charger_extension_line_n_setting, 609) \
X(a, STATIC,   OPTIONAL, UENUM,    sp_charger_driving_chg_setting, 610) \
X(a, STATIC,   OPTIONAL, FLOAT,    sp_charger_car_batt_chg_amp_limit, 624) \
X(a, STATIC,   OPTIONAL, FLOAT,    sp_charger_dev_batt_chg_amp_limit, 625) \
X(a, STATIC,   OPTIONAL, MESSAGE,  sp_charger_dev_batt_chg_xt60_setting, 626) \
X(a, STATIC,   OPTIONAL, FLOAT,    sp_charger_car_batt_chg_amp_max, 723) \
X(a, STATIC,   OPTIONAL, UINT32,   sp_charger_car_batt_urgent_chg_state, 724) \
X(a, STATIC,   OPTIONAL, FLOAT,    sp_charger_dev_batt_chg_amp_max, 725) \
X(a, STATIC,   OPTIONAL, BOOL,     sp_charger_car_batt_urgent_chg_switch, 726)
#define dc009_apl_comm_DisplayPropertyUpload_CALLBACK pb_default_field_callback
#define dc009_apl_comm_DisplayPropertyUpload_DEFAULT NULL
#define dc009_apl_comm_DisplayPropertyUpload_sp_charger_dev_batt_chg_xt60_setting_MSGTYPE dc009_apl_comm_SpChargerDevBattChgXt60Setting

#define dc009_apl_comm_RuntimePropertyUpload_FIELDLIST(X, a) \
X(a, STATIC,   OPTIONAL, FLOAT,    plug_in_info_dc_bidi_vol, 103) \
X(a, STATIC,   OPTIONAL, FLOAT,    plug_in_info_dc_bidi_amp, 104) \
X(a, STATIC,   OPTIONAL, INT32,    display_property_full_upload_period, 293) \
X(a, STATIC,   OPTIONAL, INT32,    display_property_incremental_upload_period, 294) \
X(a, STATIC,   OPTIONAL, INT32,    runtime_property_full_upload_period, 295) \
X(a, STATIC,   OPTIONAL, INT32,    runtime_property_incremental_upload_period, 296) \
X(a, STATIC,   OPTIONAL, FLOAT,    plug_in_info_dcp_vol, 443) \
X(a, STATIC,   OPTIONAL, FLOAT,    plug_in_info_dcp_amp, 448)
#define dc009_apl_comm_RuntimePropertyUpload_CALLBACK NULL
#define dc009_apl_comm_RuntimePropertyUpload_DEFAULT NULL

#define dc009_apl_comm_DevRequest_FIELDLIST(X, a) \
X(a, STATIC,   OPTIONAL, UINT32,   dev_utc_time,      1) \
X(a, STATIC,   OPTIONAL, FLOAT,    dev_utc_timezone,   2) \
X(a, STATIC,   OPTIONAL, BOOL,     require_property_upload_period,   3) \
X(a, STATIC,   OPTIONAL, BOOL,     require_time_service,   5)
#define dc009_apl_comm_DevRequest_CALLBACK NULL
#define dc009_apl_comm_DevRequest_DEFAULT NULL

#define dc009_apl_comm_DevRequestAck_FIELDLIST(X, a) \
X(a, STATIC,   OPTIONAL, UINT32,   request_id,        1) \
X(a, STATIC,   OPTIONAL, UINT32,   require_ok,        2) \
X(a, STATIC,   OPTIONAL, MESSAGE,  property_upload_period,   3)
#define dc009_apl_comm_DevRequestAck_CALLBACK NULL
#define dc009_apl_comm_DevRequestAck_DEFAULT NULL
#define dc009_apl_comm_DevRequestAck_property_upload_period_MSGTYPE dc009_apl_comm_PropertyUploadPeriod

extern const pb_msgdesc_t dc009_apl_comm_EventPush_msg;
extern const pb_msgdesc_t dc009_apl_comm_EventPush_LogItem_msg;
extern const pb_msgdesc_t dc009_apl_comm_EventAck_msg;
extern const pb_msgdesc_t dc009_apl_comm_PropertyUploadPeriod_msg;
extern const pb_msgdesc_t dc009_apl_comm_SpChargerDevBattChgXt60Setting_msg;
extern const pb_msgdesc_t dc009_apl_comm_ConfigWrite_msg;
extern const pb_msgdesc_t dc009_apl_comm_ConfigWriteAck_msg;
extern const pb_msgdesc_t dc009_apl_comm_ConfigRead_msg;
extern const pb_msgdesc_t dc009_apl_comm_ConfigReadAck_msg;
extern const pb_msgdesc_t dc009_apl_comm_DisplayPropertyUpload_msg;
extern const pb_msgdesc_t dc009_apl_comm_RuntimePropertyUpload_msg;
extern const pb_msgdesc_t dc009_apl_comm_DevRequest_msg;
extern const pb_msgdesc_t dc009_apl_comm_DevRequestAck_msg;

/* Defines for backwards compatibility with code written before nanopb-0.4.0 */
#define dc009_apl_comm_EventPush_fields &dc009_apl_comm_EventPush_msg
#define dc009_apl_comm_EventPush_LogItem_fields &dc009_apl_comm_EventPush_LogItem_msg
#define dc009_apl_comm_EventAck_fields &dc009_apl_comm_EventAck_msg
#define dc009_apl_comm_PropertyUploadPeriod_fields &dc009_apl_comm_PropertyUploadPeriod_msg
#define dc009_apl_comm_SpChargerDevBattChgXt60Setting_fields &dc009_apl_comm_SpChargerDevBattChgXt60Setting_msg
#define dc009_apl_comm_ConfigWrite_fields &dc009_apl_comm_ConfigWrite_msg
#define dc009_apl_comm_ConfigWriteAck_fields &dc009_apl_comm_ConfigWriteAck_msg
#define dc009_apl_comm_ConfigRead_fields &dc009_apl_comm_ConfigRead_msg
#define dc009_apl_comm_ConfigReadAck_fields &dc009_apl_comm_ConfigReadAck_msg
#define dc009_apl_comm_DisplayPropertyUpload_fields &dc009_apl_comm_DisplayPropertyUpload_msg
#define dc009_apl_comm_RuntimePropertyUpload_fields &dc009_apl_comm_RuntimePropertyUpload_msg
#define dc009_apl_comm_DevRequest_fields &dc009_apl_comm_DevRequest_msg
#define dc009_apl_comm_DevRequestAck_fields &dc009_apl_comm_DevRequestAck_msg

/* Maximum encoded size of messages (where known) */
/* dc009_apl_comm_EventPush_size depends on runtime parameters */
/* dc009_apl_comm_EventPush_LogItem_size depends on runtime parameters */
/* dc009_apl_comm_ConfigRead_size depends on runtime parameters */
/* dc009_apl_comm_DisplayPropertyUpload_size depends on runtime parameters */
#define DC009_APL_COMM_DC009_APL_COMM_PB_H_MAX_SIZE dc009_apl_comm_ConfigWriteAck_size
#define dc009_apl_comm_ConfigReadAck_size        17
#define dc009_apl_comm_ConfigWriteAck_size       145
#define dc009_apl_comm_ConfigWrite_size          137
#define dc009_apl_comm_DevRequestAck_size        58
#define dc009_apl_comm_DevRequest_size           15
#define dc009_apl_comm_EventAck_size             18
#define dc009_apl_comm_PropertyUploadPeriod_size 44
#define dc009_apl_comm_RuntimePropertyUpload_size 72
#define dc009_apl_comm_SpChargerDevBattChgXt60Setting_size 4

#ifdef __cplusplus
} /* extern "C" */
#endif

#endif
