/* Automatically generated nanopb constant definitions */
/* Generated by nanopb-0.4.9.1 */

#include "dc009_apl_comm.pb.h"
#if PB_PROTO_HEADER_VERSION != 40
#error Regenerate this file with the current version of nanopb generator.
#endif

PB_BIND(dc009_apl_comm_EventPush, dc009_apl_comm_EventPush, AUTO)


PB_BIND(dc009_apl_comm_EventPush_LogItem, dc009_apl_comm_EventPush_LogItem, AUTO)


PB_BIND(dc009_apl_comm_EventAck, dc009_apl_comm_EventAck, AUTO)


PB_BIND(dc009_apl_comm_PropertyUploadPeriod, dc009_apl_comm_PropertyUploadPeriod, AUTO)


PB_BIND(dc009_apl_comm_SpChargerDevBattChgXt60Setting, dc009_apl_comm_SpChargerDevBattChgXt60Setting, AUTO)


PB_BIND(dc009_apl_comm_ConfigWrite, dc009_apl_comm_ConfigWrite, 2)


PB_BIND(dc009_apl_comm_ConfigWriteAck, dc009_apl_comm_ConfigWriteAck, 2)


PB_BIND(dc009_apl_comm_ConfigRead, dc009_apl_comm_ConfigRead, AUTO)


PB_BIND(dc009_apl_comm_ConfigReadAck, dc009_apl_comm_ConfigReadAck, AUTO)


PB_BIND(dc009_apl_comm_DisplayPropertyUpload, dc009_apl_comm_DisplayPropertyUpload, 2)


PB_BIND(dc009_apl_comm_RuntimePropertyUpload, dc009_apl_comm_RuntimePropertyUpload, 2)


PB_BIND(dc009_apl_comm_DevRequest, dc009_apl_comm_DevRequest, AUTO)


PB_BIND(dc009_apl_comm_DevRequestAck, dc009_apl_comm_DevRequestAck, AUTO)
