/* Automatically generated nanopb constant definitions */
/* Generated by nanopb-0.4.9.1 */

#include "mr521.pb.h"
#if PB_PROTO_HEADER_VERSION != 40
#error Regenerate this file with the current version of nanopb generator.
#endif

PB_BIND(mr521_EventPush, mr521_EventPush, AUTO)


PB_BIND(mr521_EventPush_LogItem, mr521_EventPush_LogItem, AUTO)


PB_BIND(mr521_EventAck, mr521_EventAck, AUTO)


PB_BIND(mr521_ReqTouStrategy, mr521_ReqTouStrategy, AUTO)


PB_BIND(mr521_CfgBeep, mr521_CfgBeep, AUTO)


PB_BIND(mr521_CfgAcOutAlwaysOn, mr521_CfgAcOutAlwaysOn, AUTO)


PB_BIND(mr521_CfgBmsPowerOffWriteAck, mr521_CfgBmsPowerOffWriteAck, AUTO)


PB_BIND(mr521_CfgBmsPushWrite, mr521_CfgBmsPushWrite, AUTO)


PB_BIND(mr521_CfgBmsPushWriteAck, mr521_CfgBmsPushWriteAck, AUTO)


PB_BIND(mr521_SetTimeTaskWrite, mr521_SetTimeTaskWrite, AUTO)


PB_BIND(mr521_SetTimeTaskWriteAck, mr521_SetTimeTaskWriteAck, AUTO)


PB_BIND(mr521_GetAllTimeTaskReadck, mr521_GetAllTimeTaskReadck, AUTO)


PB_BIND(mr521_CfgEnergyBackup, mr521_CfgEnergyBackup, AUTO)


PB_BIND(mr521_CfgAcHvAlwaysOn, mr521_CfgAcHvAlwaysOn, AUTO)


PB_BIND(mr521_CfgAcLvAlwaysOn, mr521_CfgAcLvAlwaysOn, AUTO)


PB_BIND(mr521_CfgTouStrategy, mr521_CfgTouStrategy, AUTO)


PB_BIND(mr521_CfgRj45CommcService, mr521_CfgRj45CommcService, AUTO)


PB_BIND(mr521_CfgStormPattern, mr521_CfgStormPattern, AUTO)


PB_BIND(mr521_CfgGeneratorMpptHybridMode, mr521_CfgGeneratorMpptHybridMode, AUTO)


PB_BIND(mr521_CfgGeneratorCareMode, mr521_CfgGeneratorCareMode, AUTO)


PB_BIND(mr521_CfgEnergyStrategyOperateMode, mr521_CfgEnergyStrategyOperateMode, AUTO)


PB_BIND(mr521_InstallmentPaymentServeBelone, mr521_InstallmentPaymentServeBelone, AUTO)


PB_BIND(mr521_InstallmentPaymentServe, mr521_InstallmentPaymentServe, AUTO)


PB_BIND(mr521_ResvInfo, mr521_ResvInfo, AUTO)


PB_BIND(mr521_ResetMiddlemenDeliverySetting, mr521_ResetMiddlemenDeliverySetting, AUTO)


PB_BIND(mr521_PropertyUploadPeriod, mr521_PropertyUploadPeriod, AUTO)


PB_BIND(mr521_PvDcChgSetting, mr521_PvDcChgSetting, AUTO)


PB_BIND(mr521_PvDcChgSettingList, mr521_PvDcChgSettingList, AUTO)


PB_BIND(mr521_PvChgMaxItem, mr521_PvChgMaxItem, AUTO)


PB_BIND(mr521_PvChgMaxList, mr521_PvChgMaxList, AUTO)


PB_BIND(mr521_TimeTaskItemV2, mr521_TimeTaskItemV2, AUTO)


PB_BIND(mr521_TimeTaskItemV2List, mr521_TimeTaskItemV2List, AUTO)


PB_BIND(mr521_StatisticsRecordItem, mr521_StatisticsRecordItem, AUTO)


PB_BIND(mr521_DisplayStatisticsRecordList, mr521_DisplayStatisticsRecordList, AUTO)


PB_BIND(mr521_RuntimeStatisticsRecordList, mr521_RuntimeStatisticsRecordList, AUTO)


PB_BIND(mr521_ErrcodeRecordItem, mr521_ErrcodeRecordItem, AUTO)


PB_BIND(mr521_ErrcodeRecordList, mr521_ErrcodeRecordList, AUTO)


PB_BIND(mr521_WirelessCoordinateList, mr521_WirelessCoordinateList, AUTO)


PB_BIND(mr521_TimeTaskParamDetail, mr521_TimeTaskParamDetail, AUTO)


PB_BIND(mr521_ConfigWrite, mr521_ConfigWrite, 2)


PB_BIND(mr521_ConfigWriteAck, mr521_ConfigWriteAck, 2)


PB_BIND(mr521_ConfigRead, mr521_ConfigRead, AUTO)


PB_BIND(mr521_ConfigReadAck, mr521_ConfigReadAck, 2)


PB_BIND(mr521_DisplayPropertyUpload, mr521_DisplayPropertyUpload, 2)


PB_BIND(mr521_RuntimePropertyUpload, mr521_RuntimePropertyUpload, 2)


PB_BIND(mr521_DevRequest, mr521_DevRequest, AUTO)


PB_BIND(mr521_DevRequestAck, mr521_DevRequestAck, AUTO)
