/* Automatically generated nanopb constant definitions */
/* Generated by nanopb-0.4.9.1 */

#include "pd335_bms_bp.pb.h"
#if PB_PROTO_HEADER_VERSION != 40
#error Regenerate this file with the current version of nanopb generator.
#endif

PB_BIND(pd335_bms_bp_BMSHeartBeatReport, pd335_bms_bp_BMSHeartBeatReport, 2)


PB_BIND(pd335_bms_bp_ems_heartbeat_pack_v1p0_t, pd335_bms_bp_ems_heartbeat_pack_v1p0_t, AUTO)


PB_BIND(pd335_bms_bp_ems_heartbeat_pack_v1p3_t, pd335_bms_bp_ems_heartbeat_pack_v1p3_t, AUTO)


PB_BIND(pd335_bms_bp_CMSHeartBeatReport, pd335_bms_bp_CMSHeartBeatReport, 2)


PB_BIND(pd335_bms_bp_AppRuquestBpEuLawData, pd335_bms_bp_AppRuquestBpEuLawData, AUTO)


PB_BIND(pd335_bms_bp_AppRuquestBpEuLawDataAck, pd335_bms_bp_AppRuquestBpEuLawDataAck, AUTO)
