/* Automatically generated nanopb header */
/* Generated by nanopb-0.4.9.1 */

#ifndef PB_PD335_BMS_BP_PYTHON_IMPLEMENTATION_PROTO_PD335_BMS_BP_PB_H_INCLUDED
#define PB_PD335_BMS_BP_PYTHON_IMPLEMENTATION_PROTO_PD335_BMS_BP_PB_H_INCLUDED
#include <pb.h>

#if PB_PROTO_HEADER_VERSION != 40
#error Regenerate this file with the current version of nanopb generator.
#endif

/* Enum definitions */
typedef enum _pd335_bms_bp_AppDateType {
    pd335_bms_bp_AppDateType_NONE_SET = 0,
    pd335_bms_bp_AppDateType_APP_AUTO_SET = 1,
    pd335_bms_bp_AppDateType_APP_MANUAL_SET = 2,
    pd335_bms_bp_AppDateType_BMS_AUTO_SET = 3
} pd335_bms_bp_AppDateType;

typedef enum _pd335_bms_bp_BpResetType {
    pd335_bms_bp_BpResetType_NONE_RESET_VAL = 0,
    pd335_bms_bp_BpResetType_HAS_RESET_VAL = 1,
    pd335_bms_bp_BpResetType_NEED_RESET_VAL = 2,
    pd335_bms_bp_BpResetType_MASTER_RESET = 3
} pd335_bms_bp_BpResetType;

/* Struct definitions */
typedef struct _pd335_bms_bp_BMSHeartBeatReport {
    bool has_num;
    uint32_t num;
    bool has_type;
    uint32_t type;
    bool has_cell_id;
    uint32_t cell_id;
    bool has_err_code;
    uint32_t err_code;
    bool has_sys_ver;
    uint32_t sys_ver;
    bool has_soc;
    uint32_t soc;
    bool has_vol;
    uint32_t vol;
    bool has_amp;
    int32_t amp;
    bool has_temp;
    int32_t temp;
    bool has_open_bms_flag;
    uint32_t open_bms_flag;
    bool has_design_cap;
    uint32_t design_cap;
    bool has_remain_cap;
    uint32_t remain_cap;
    bool has_full_cap;
    uint32_t full_cap;
    bool has_cycles;
    uint32_t cycles;
    bool has_soh;
    uint32_t soh;
    bool has_max_cell_vol;
    uint32_t max_cell_vol;
    bool has_min_cell_vol;
    uint32_t min_cell_vol;
    bool has_max_cell_temp;
    int32_t max_cell_temp;
    bool has_min_cell_temp;
    int32_t min_cell_temp;
    bool has_max_mos_temp;
    int32_t max_mos_temp;
    bool has_min_mos_temp;
    int32_t min_mos_temp;
    bool has_bms_fault;
    uint32_t bms_fault;
    bool has_bq_sys_stat_reg;
    uint32_t bq_sys_stat_reg;
    bool has_tag_chg_amp;
    uint32_t tag_chg_amp;
    bool has_f32_show_soc;
    float f32_show_soc;
    bool has_input_watts;
    uint32_t input_watts;
    bool has_output_watts;
    uint32_t output_watts;
    bool has_remain_time;
    uint32_t remain_time;
    bool has_mos_state;
    uint32_t mos_state;
    bool has_balance_state;
    uint32_t balance_state;
    bool has_max_vol_diff;
    uint32_t max_vol_diff;
    bool has_cell_series_num;
    uint32_t cell_series_num;
    pb_callback_t cell_vol;
    bool has_cell_ntc_num;
    uint32_t cell_ntc_num;
    pb_callback_t cell_temp;
    pb_callback_t hw_ver;
    bool has_bms_heartbeat_ver;
    uint32_t bms_heartbeat_ver;
    bool has_ecloud_ocv;
    uint32_t ecloud_ocv;
    pb_callback_t bms_sn;
    bool has_product_type;
    uint32_t product_type;
    bool has_product_detail;
    uint32_t product_detail;
    bool has_act_soc;
    float act_soc;
    bool has_diff_soc;
    float diff_soc;
    bool has_target_soc;
    float target_soc;
    bool has_sys_loader_ver;
    uint32_t sys_loader_ver;
    bool has_sys_state;
    uint32_t sys_state;
    bool has_chg_dsg_state;
    uint32_t chg_dsg_state;
    bool has_all_err_code;
    uint32_t all_err_code;
    bool has_all_bms_fault;
    uint32_t all_bms_fault;
    bool has_accu_chg_cap;
    uint32_t accu_chg_cap;
    bool has_accu_dsg_cap;
    uint32_t accu_dsg_cap;
    bool has_real_soh;
    float real_soh;
    bool has_calendar_soh;
    float calendar_soh;
    bool has_cycle_soh;
    float cycle_soh;
    bool has_mos_ntc_num;
    uint32_t mos_ntc_num;
    pb_callback_t mos_temp;
    bool has_env_ntc_num;
    uint32_t env_ntc_num;
    pb_callback_t env_temp;
    bool has_heatfilm_ntc_num;
    uint32_t heatfilm_ntc_num;
    pb_callback_t heatfilm_temp;
    bool has_cur_sensor_ntc_num;
    uint32_t cur_sensor_ntc_num;
    pb_callback_t cur_sensor_temp;
    bool has_max_env_temp;
    int32_t max_env_temp;
    bool has_min_env_temp;
    int32_t min_env_temp;
    bool has_max_heatfilm_temp;
    int32_t max_heatfilm_temp;
    bool has_min_heatfilm_temp;
    int32_t min_heatfilm_temp;
    bool has_max_cur_sensor_temp;
    int32_t max_cur_sensor_temp;
    bool has_min_cur_sensor_temp;
    int32_t min_cur_sensor_temp;
    bool has_balance_cmd;
    uint32_t balance_cmd;
    pb_callback_t remain_balance_time;
    bool has_afe_sys_status;
    uint32_t afe_sys_status;
    bool has_mcu_pin_in_status;
    uint32_t mcu_pin_in_status;
    bool has_mcu_pin_out_status;
    uint32_t mcu_pin_out_status;
    bool has_bms_alarm_state1;
    uint32_t bms_alarm_state1;
    bool has_bms_alarm_state2;
    uint32_t bms_alarm_state2;
    bool has_bms_protect_state1;
    uint32_t bms_protect_state1;
    bool has_bms_protect_state2;
    uint32_t bms_protect_state2;
    bool has_bms_fault_state;
    uint32_t bms_fault_state;
    bool has_accu_chg_energy;
    uint32_t accu_chg_energy;
    bool has_accu_dsg_energy;
    uint32_t accu_dsg_energy;
    pb_callback_t pack_sn;
    bool has_water_in_flag;
    uint32_t water_in_flag;
} pd335_bms_bp_BMSHeartBeatReport;

typedef struct _pd335_bms_bp_ems_heartbeat_pack_v1p0_t {
    bool has_chg_state;
    uint32_t chg_state;
    bool has_chg_cmd;
    uint32_t chg_cmd;
    bool has_dsg_cmd;
    uint32_t dsg_cmd;
    bool has_chg_vol;
    uint32_t chg_vol;
    bool has_chg_amp;
    uint32_t chg_amp;
    bool has_fan_level;
    uint32_t fan_level;
    bool has_max_charge_soc;
    uint32_t max_charge_soc;
    bool has_bms_model;
    uint32_t bms_model;
    bool has_lcd_show_soc;
    uint32_t lcd_show_soc;
    bool has_open_ups_flag;
    uint32_t open_ups_flag;
    bool has_bms_warning_state;
    uint32_t bms_warning_state;
    bool has_chg_remain_time;
    uint32_t chg_remain_time;
    bool has_dsg_remain_time;
    uint32_t dsg_remain_time;
    bool has_ems_is_normal_flag;
    uint32_t ems_is_normal_flag;
    bool has_f32_lcd_show_soc;
    float f32_lcd_show_soc;
    pb_callback_t bms_is_connt;
    bool has_max_available_num;
    uint32_t max_available_num;
    bool has_open_bms_idx;
    uint32_t open_bms_idx;
    bool has_para_vol_min;
    uint32_t para_vol_min;
    bool has_para_vol_max;
    uint32_t para_vol_max;
    bool has_min_dsg_soc;
    uint32_t min_dsg_soc;
    bool has_min_open_oil_eb_soc;
    uint32_t min_open_oil_eb_soc;
    bool has_max_close_oil_eb_soc;
    uint32_t max_close_oil_eb_soc;
} pd335_bms_bp_ems_heartbeat_pack_v1p0_t;

typedef struct _pd335_bms_bp_ems_heartbeat_pack_v1p3_t {
    bool has_chg_disable_cond;
    uint32_t chg_disable_cond;
    bool has_dsg_disable_cond;
    uint32_t dsg_disable_cond;
    bool has_chg_line_plug_in_flag;
    uint32_t chg_line_plug_in_flag;
    bool has_sys_chg_dsg_state;
    uint32_t sys_chg_dsg_state;
    bool has_ems_heartbeat_ver;
    uint32_t ems_heartbeat_ver;
} pd335_bms_bp_ems_heartbeat_pack_v1p3_t;

typedef struct _pd335_bms_bp_CMSHeartBeatReport {
    bool has_v1p0;
    pd335_bms_bp_ems_heartbeat_pack_v1p0_t v1p0;
    bool has_v1p3;
    pd335_bms_bp_ems_heartbeat_pack_v1p3_t v1p3;
} pd335_bms_bp_CMSHeartBeatReport;

typedef struct _pd335_bms_bp_AppRuquestBpEuLawData {
    pb_callback_t pack_sn;
    bool has_app_to_bms_launch_date;
    uint32_t app_to_bms_launch_date;
    bool has_app_launch_date_set_type;
    uint32_t app_launch_date_set_type;
    bool has_app_to_bms_reset_flag;
    uint32_t app_to_bms_reset_flag;
    bool has_bms_data_upload_en;
    uint32_t bms_data_upload_en;
} pd335_bms_bp_AppRuquestBpEuLawData;

typedef struct _pd335_bms_bp_AppRuquestBpEuLawDataAck {
    pb_callback_t bms_sn;
    bool has_soh;
    uint32_t soh;
    bool has_accu_chg_cap;
    uint32_t accu_chg_cap;
    bool has_accu_dsg_cap;
    uint32_t accu_dsg_cap;
    bool has_accu_chg_energy;
    uint32_t accu_chg_energy;
    bool has_accu_dsg_energy;
    uint32_t accu_dsg_energy;
    bool has_deep_dsg_cnt;
    uint32_t deep_dsg_cnt;
    bool has_high_temp_use_time;
    uint32_t high_temp_use_time;
    bool has_low_temp_use_time;
    uint32_t low_temp_use_time;
    bool has_high_temp_chg_time;
    uint32_t high_temp_chg_time;
    bool has_low_temp_chg_time;
    uint32_t low_temp_chg_time;
    bool has_bp_launch_date;
    uint32_t bp_launch_date;
    bool has_bp_cycles;
    uint32_t bp_cycles;
    bool has_bp_power_capability;
    float bp_power_capability;
    bool has_bp_round_trip_eff;
    float bp_round_trip_eff;
    bool has_bp_self_dsg_rate;
    float bp_self_dsg_rate;
    bool has_bp_ohm_res;
    float bp_ohm_res;
    bool has_bp_reset_flag;
    pd335_bms_bp_BpResetType bp_reset_flag;
    bool has_bp_launch_date_flag;
    pd335_bms_bp_AppDateType bp_launch_date_flag;
    bool has_num;
    uint32_t num;
} pd335_bms_bp_AppRuquestBpEuLawDataAck;


#ifdef __cplusplus
extern "C" {
#endif

/* Helper constants for enums */
#define _pd335_bms_bp_AppDateType_MIN pd335_bms_bp_AppDateType_NONE_SET
#define _pd335_bms_bp_AppDateType_MAX pd335_bms_bp_AppDateType_BMS_AUTO_SET
#define _pd335_bms_bp_AppDateType_ARRAYSIZE ((pd335_bms_bp_AppDateType)(pd335_bms_bp_AppDateType_BMS_AUTO_SET+1))

#define _pd335_bms_bp_BpResetType_MIN pd335_bms_bp_BpResetType_NONE_RESET_VAL
#define _pd335_bms_bp_BpResetType_MAX pd335_bms_bp_BpResetType_MASTER_RESET
#define _pd335_bms_bp_BpResetType_ARRAYSIZE ((pd335_bms_bp_BpResetType)(pd335_bms_bp_BpResetType_MASTER_RESET+1))






#define pd335_bms_bp_AppRuquestBpEuLawDataAck_bp_reset_flag_ENUMTYPE pd335_bms_bp_BpResetType
#define pd335_bms_bp_AppRuquestBpEuLawDataAck_bp_launch_date_flag_ENUMTYPE pd335_bms_bp_AppDateType


/* Initializer values for message structs */
#define pd335_bms_bp_BMSHeartBeatReport_init_default {false, 0, false, 0, false, 0, false, 0, false, 0, false, 0, false, 0, false, 0, false, 0, false, 0, false, 0, false, 0, false, 0, false, 0, false, 0, false, 0, false, 0, false, 0, false, 0, false, 0, false, 0, false, 0, false, 0, false, 0, false, 0, false, 0, false, 0, false, 0, false, 0, false, 0, false, 0, false, 0, {{NULL}, NULL}, false, 0, {{NULL}, NULL}, {{NULL}, NULL}, false, 0, false, 0, {{NULL}, NULL}, false, 0, false, 0, false, 0, false, 0, false, 0, false, 0, false, 0, false, 0, false, 0, false, 0, false, 0, false, 0, false, 0, false, 0, false, 0, false, 0, {{NULL}, NULL}, false, 0, {{NULL}, NULL}, false, 0, {{NULL}, NULL}, false, 0, {{NULL}, NULL}, false, 0, false, 0, false, 0, false, 0, false, 0, false, 0, false, 0, {{NULL}, NULL}, false, 0, false, 0, false, 0, false, 0, false, 0, false, 0, false, 0, false, 0, false, 0, false, 0, {{NULL}, NULL}, false, 0}
#define pd335_bms_bp_ems_heartbeat_pack_v1p0_t_init_default {false, 0, false, 0, false, 0, false, 0, false, 0, false, 0, false, 0, false, 0, false, 0, false, 0, false, 0, false, 0, false, 0, false, 0, false, 0, {{NULL}, NULL}, false, 0, false, 0, false, 0, false, 0, false, 0, false, 0, false, 0}
#define pd335_bms_bp_ems_heartbeat_pack_v1p3_t_init_default {false, 0, false, 0, false, 0, false, 0, false, 0}
#define pd335_bms_bp_CMSHeartBeatReport_init_default {false, pd335_bms_bp_ems_heartbeat_pack_v1p0_t_init_default, false, pd335_bms_bp_ems_heartbeat_pack_v1p3_t_init_default}
#define pd335_bms_bp_AppRuquestBpEuLawData_init_default {{{NULL}, NULL}, false, 0, false, 0, false, 0, false, 0}
#define pd335_bms_bp_AppRuquestBpEuLawDataAck_init_default {{{NULL}, NULL}, false, 0, false, 0, false, 0, false, 0, false, 0, false, 0, false, 0, false, 0, false, 0, false, 0, false, 0, false, 0, false, 0, false, 0, false, 0, false, 0, false, _pd335_bms_bp_BpResetType_MIN, false, _pd335_bms_bp_AppDateType_MIN, false, 0}
#define pd335_bms_bp_BMSHeartBeatReport_init_zero {false, 0, false, 0, false, 0, false, 0, false, 0, false, 0, false, 0, false, 0, false, 0, false, 0, false, 0, false, 0, false, 0, false, 0, false, 0, false, 0, false, 0, false, 0, false, 0, false, 0, false, 0, false, 0, false, 0, false, 0, false, 0, false, 0, false, 0, false, 0, false, 0, false, 0, false, 0, false, 0, {{NULL}, NULL}, false, 0, {{NULL}, NULL}, {{NULL}, NULL}, false, 0, false, 0, {{NULL}, NULL}, false, 0, false, 0, false, 0, false, 0, false, 0, false, 0, false, 0, false, 0, false, 0, false, 0, false, 0, false, 0, false, 0, false, 0, false, 0, false, 0, {{NULL}, NULL}, false, 0, {{NULL}, NULL}, false, 0, {{NULL}, NULL}, false, 0, {{NULL}, NULL}, false, 0, false, 0, false, 0, false, 0, false, 0, false, 0, false, 0, {{NULL}, NULL}, false, 0, false, 0, false, 0, false, 0, false, 0, false, 0, false, 0, false, 0, false, 0, false, 0, {{NULL}, NULL}, false, 0}
#define pd335_bms_bp_ems_heartbeat_pack_v1p0_t_init_zero {false, 0, false, 0, false, 0, false, 0, false, 0, false, 0, false, 0, false, 0, false, 0, false, 0, false, 0, false, 0, false, 0, false, 0, false, 0, {{NULL}, NULL}, false, 0, false, 0, false, 0, false, 0, false, 0, false, 0, false, 0}
#define pd335_bms_bp_ems_heartbeat_pack_v1p3_t_init_zero {false, 0, false, 0, false, 0, false, 0, false, 0}
#define pd335_bms_bp_CMSHeartBeatReport_init_zero {false, pd335_bms_bp_ems_heartbeat_pack_v1p0_t_init_zero, false, pd335_bms_bp_ems_heartbeat_pack_v1p3_t_init_zero}
#define pd335_bms_bp_AppRuquestBpEuLawData_init_zero {{{NULL}, NULL}, false, 0, false, 0, false, 0, false, 0}
#define pd335_bms_bp_AppRuquestBpEuLawDataAck_init_zero {{{NULL}, NULL}, false, 0, false, 0, false, 0, false, 0, false, 0, false, 0, false, 0, false, 0, false, 0, false, 0, false, 0, false, 0, false, 0, false, 0, false, 0, false, 0, false, _pd335_bms_bp_BpResetType_MIN, false, _pd335_bms_bp_AppDateType_MIN, false, 0}

/* Field tags (for use in manual encoding/decoding) */
#define pd335_bms_bp_BMSHeartBeatReport_num_tag  1
#define pd335_bms_bp_BMSHeartBeatReport_type_tag 2
#define pd335_bms_bp_BMSHeartBeatReport_cell_id_tag 3
#define pd335_bms_bp_BMSHeartBeatReport_err_code_tag 4
#define pd335_bms_bp_BMSHeartBeatReport_sys_ver_tag 5
#define pd335_bms_bp_BMSHeartBeatReport_soc_tag  6
#define pd335_bms_bp_BMSHeartBeatReport_vol_tag  7
#define pd335_bms_bp_BMSHeartBeatReport_amp_tag  8
#define pd335_bms_bp_BMSHeartBeatReport_temp_tag 9
#define pd335_bms_bp_BMSHeartBeatReport_open_bms_flag_tag 10
#define pd335_bms_bp_BMSHeartBeatReport_design_cap_tag 11
#define pd335_bms_bp_BMSHeartBeatReport_remain_cap_tag 12
#define pd335_bms_bp_BMSHeartBeatReport_full_cap_tag 13
#define pd335_bms_bp_BMSHeartBeatReport_cycles_tag 14
#define pd335_bms_bp_BMSHeartBeatReport_soh_tag  15
#define pd335_bms_bp_BMSHeartBeatReport_max_cell_vol_tag 16
#define pd335_bms_bp_BMSHeartBeatReport_min_cell_vol_tag 17
#define pd335_bms_bp_BMSHeartBeatReport_max_cell_temp_tag 18
#define pd335_bms_bp_BMSHeartBeatReport_min_cell_temp_tag 19
#define pd335_bms_bp_BMSHeartBeatReport_max_mos_temp_tag 20
#define pd335_bms_bp_BMSHeartBeatReport_min_mos_temp_tag 21
#define pd335_bms_bp_BMSHeartBeatReport_bms_fault_tag 22
#define pd335_bms_bp_BMSHeartBeatReport_bq_sys_stat_reg_tag 23
#define pd335_bms_bp_BMSHeartBeatReport_tag_chg_amp_tag 24
#define pd335_bms_bp_BMSHeartBeatReport_f32_show_soc_tag 25
#define pd335_bms_bp_BMSHeartBeatReport_input_watts_tag 26
#define pd335_bms_bp_BMSHeartBeatReport_output_watts_tag 27
#define pd335_bms_bp_BMSHeartBeatReport_remain_time_tag 28
#define pd335_bms_bp_BMSHeartBeatReport_mos_state_tag 29
#define pd335_bms_bp_BMSHeartBeatReport_balance_state_tag 30
#define pd335_bms_bp_BMSHeartBeatReport_max_vol_diff_tag 31
#define pd335_bms_bp_BMSHeartBeatReport_cell_series_num_tag 32
#define pd335_bms_bp_BMSHeartBeatReport_cell_vol_tag 33
#define pd335_bms_bp_BMSHeartBeatReport_cell_ntc_num_tag 34
#define pd335_bms_bp_BMSHeartBeatReport_cell_temp_tag 35
#define pd335_bms_bp_BMSHeartBeatReport_hw_ver_tag 36
#define pd335_bms_bp_BMSHeartBeatReport_bms_heartbeat_ver_tag 37
#define pd335_bms_bp_BMSHeartBeatReport_ecloud_ocv_tag 38
#define pd335_bms_bp_BMSHeartBeatReport_bms_sn_tag 39
#define pd335_bms_bp_BMSHeartBeatReport_product_type_tag 40
#define pd335_bms_bp_BMSHeartBeatReport_product_detail_tag 41
#define pd335_bms_bp_BMSHeartBeatReport_act_soc_tag 42
#define pd335_bms_bp_BMSHeartBeatReport_diff_soc_tag 43
#define pd335_bms_bp_BMSHeartBeatReport_target_soc_tag 44
#define pd335_bms_bp_BMSHeartBeatReport_sys_loader_ver_tag 45
#define pd335_bms_bp_BMSHeartBeatReport_sys_state_tag 46
#define pd335_bms_bp_BMSHeartBeatReport_chg_dsg_state_tag 47
#define pd335_bms_bp_BMSHeartBeatReport_all_err_code_tag 48
#define pd335_bms_bp_BMSHeartBeatReport_all_bms_fault_tag 49
#define pd335_bms_bp_BMSHeartBeatReport_accu_chg_cap_tag 50
#define pd335_bms_bp_BMSHeartBeatReport_accu_dsg_cap_tag 51
#define pd335_bms_bp_BMSHeartBeatReport_real_soh_tag 52
#define pd335_bms_bp_BMSHeartBeatReport_calendar_soh_tag 53
#define pd335_bms_bp_BMSHeartBeatReport_cycle_soh_tag 54
#define pd335_bms_bp_BMSHeartBeatReport_mos_ntc_num_tag 55
#define pd335_bms_bp_BMSHeartBeatReport_mos_temp_tag 56
#define pd335_bms_bp_BMSHeartBeatReport_env_ntc_num_tag 57
#define pd335_bms_bp_BMSHeartBeatReport_env_temp_tag 58
#define pd335_bms_bp_BMSHeartBeatReport_heatfilm_ntc_num_tag 59
#define pd335_bms_bp_BMSHeartBeatReport_heatfilm_temp_tag 60
#define pd335_bms_bp_BMSHeartBeatReport_cur_sensor_ntc_num_tag 61
#define pd335_bms_bp_BMSHeartBeatReport_cur_sensor_temp_tag 62
#define pd335_bms_bp_BMSHeartBeatReport_max_env_temp_tag 63
#define pd335_bms_bp_BMSHeartBeatReport_min_env_temp_tag 64
#define pd335_bms_bp_BMSHeartBeatReport_max_heatfilm_temp_tag 65
#define pd335_bms_bp_BMSHeartBeatReport_min_heatfilm_temp_tag 66
#define pd335_bms_bp_BMSHeartBeatReport_max_cur_sensor_temp_tag 67
#define pd335_bms_bp_BMSHeartBeatReport_min_cur_sensor_temp_tag 68
#define pd335_bms_bp_BMSHeartBeatReport_balance_cmd_tag 69
#define pd335_bms_bp_BMSHeartBeatReport_remain_balance_time_tag 70
#define pd335_bms_bp_BMSHeartBeatReport_afe_sys_status_tag 71
#define pd335_bms_bp_BMSHeartBeatReport_mcu_pin_in_status_tag 72
#define pd335_bms_bp_BMSHeartBeatReport_mcu_pin_out_status_tag 73
#define pd335_bms_bp_BMSHeartBeatReport_bms_alarm_state1_tag 74
#define pd335_bms_bp_BMSHeartBeatReport_bms_alarm_state2_tag 75
#define pd335_bms_bp_BMSHeartBeatReport_bms_protect_state1_tag 76
#define pd335_bms_bp_BMSHeartBeatReport_bms_protect_state2_tag 77
#define pd335_bms_bp_BMSHeartBeatReport_bms_fault_state_tag 78
#define pd335_bms_bp_BMSHeartBeatReport_accu_chg_energy_tag 79
#define pd335_bms_bp_BMSHeartBeatReport_accu_dsg_energy_tag 80
#define pd335_bms_bp_BMSHeartBeatReport_pack_sn_tag 81
#define pd335_bms_bp_BMSHeartBeatReport_water_in_flag_tag 82
#define pd335_bms_bp_ems_heartbeat_pack_v1p0_t_chg_state_tag 1
#define pd335_bms_bp_ems_heartbeat_pack_v1p0_t_chg_cmd_tag 2
#define pd335_bms_bp_ems_heartbeat_pack_v1p0_t_dsg_cmd_tag 3
#define pd335_bms_bp_ems_heartbeat_pack_v1p0_t_chg_vol_tag 4
#define pd335_bms_bp_ems_heartbeat_pack_v1p0_t_chg_amp_tag 5
#define pd335_bms_bp_ems_heartbeat_pack_v1p0_t_fan_level_tag 6
#define pd335_bms_bp_ems_heartbeat_pack_v1p0_t_max_charge_soc_tag 7
#define pd335_bms_bp_ems_heartbeat_pack_v1p0_t_bms_model_tag 8
#define pd335_bms_bp_ems_heartbeat_pack_v1p0_t_lcd_show_soc_tag 9
#define pd335_bms_bp_ems_heartbeat_pack_v1p0_t_open_ups_flag_tag 10
#define pd335_bms_bp_ems_heartbeat_pack_v1p0_t_bms_warning_state_tag 11
#define pd335_bms_bp_ems_heartbeat_pack_v1p0_t_chg_remain_time_tag 12
#define pd335_bms_bp_ems_heartbeat_pack_v1p0_t_dsg_remain_time_tag 13
#define pd335_bms_bp_ems_heartbeat_pack_v1p0_t_ems_is_normal_flag_tag 14
#define pd335_bms_bp_ems_heartbeat_pack_v1p0_t_f32_lcd_show_soc_tag 15
#define pd335_bms_bp_ems_heartbeat_pack_v1p0_t_bms_is_connt_tag 16
#define pd335_bms_bp_ems_heartbeat_pack_v1p0_t_max_available_num_tag 17
#define pd335_bms_bp_ems_heartbeat_pack_v1p0_t_open_bms_idx_tag 18
#define pd335_bms_bp_ems_heartbeat_pack_v1p0_t_para_vol_min_tag 19
#define pd335_bms_bp_ems_heartbeat_pack_v1p0_t_para_vol_max_tag 20
#define pd335_bms_bp_ems_heartbeat_pack_v1p0_t_min_dsg_soc_tag 21
#define pd335_bms_bp_ems_heartbeat_pack_v1p0_t_min_open_oil_eb_soc_tag 22
#define pd335_bms_bp_ems_heartbeat_pack_v1p0_t_max_close_oil_eb_soc_tag 23
#define pd335_bms_bp_ems_heartbeat_pack_v1p3_t_chg_disable_cond_tag 1
#define pd335_bms_bp_ems_heartbeat_pack_v1p3_t_dsg_disable_cond_tag 2
#define pd335_bms_bp_ems_heartbeat_pack_v1p3_t_chg_line_plug_in_flag_tag 3
#define pd335_bms_bp_ems_heartbeat_pack_v1p3_t_sys_chg_dsg_state_tag 4
#define pd335_bms_bp_ems_heartbeat_pack_v1p3_t_ems_heartbeat_ver_tag 5
#define pd335_bms_bp_CMSHeartBeatReport_v1p0_tag 1
#define pd335_bms_bp_CMSHeartBeatReport_v1p3_tag 2
#define pd335_bms_bp_AppRuquestBpEuLawData_pack_sn_tag 1
#define pd335_bms_bp_AppRuquestBpEuLawData_app_to_bms_launch_date_tag 2
#define pd335_bms_bp_AppRuquestBpEuLawData_app_launch_date_set_type_tag 3
#define pd335_bms_bp_AppRuquestBpEuLawData_app_to_bms_reset_flag_tag 4
#define pd335_bms_bp_AppRuquestBpEuLawData_bms_data_upload_en_tag 5
#define pd335_bms_bp_AppRuquestBpEuLawDataAck_bms_sn_tag 1
#define pd335_bms_bp_AppRuquestBpEuLawDataAck_soh_tag 2
#define pd335_bms_bp_AppRuquestBpEuLawDataAck_accu_chg_cap_tag 3
#define pd335_bms_bp_AppRuquestBpEuLawDataAck_accu_dsg_cap_tag 4
#define pd335_bms_bp_AppRuquestBpEuLawDataAck_accu_chg_energy_tag 5
#define pd335_bms_bp_AppRuquestBpEuLawDataAck_accu_dsg_energy_tag 6
#define pd335_bms_bp_AppRuquestBpEuLawDataAck_deep_dsg_cnt_tag 7
#define pd335_bms_bp_AppRuquestBpEuLawDataAck_high_temp_use_time_tag 8
#define pd335_bms_bp_AppRuquestBpEuLawDataAck_low_temp_use_time_tag 9
#define pd335_bms_bp_AppRuquestBpEuLawDataAck_high_temp_chg_time_tag 10
#define pd335_bms_bp_AppRuquestBpEuLawDataAck_low_temp_chg_time_tag 11
#define pd335_bms_bp_AppRuquestBpEuLawDataAck_bp_launch_date_tag 12
#define pd335_bms_bp_AppRuquestBpEuLawDataAck_bp_cycles_tag 13
#define pd335_bms_bp_AppRuquestBpEuLawDataAck_bp_power_capability_tag 14
#define pd335_bms_bp_AppRuquestBpEuLawDataAck_bp_round_trip_eff_tag 15
#define pd335_bms_bp_AppRuquestBpEuLawDataAck_bp_self_dsg_rate_tag 16
#define pd335_bms_bp_AppRuquestBpEuLawDataAck_bp_ohm_res_tag 17
#define pd335_bms_bp_AppRuquestBpEuLawDataAck_bp_reset_flag_tag 18
#define pd335_bms_bp_AppRuquestBpEuLawDataAck_bp_launch_date_flag_tag 19
#define pd335_bms_bp_AppRuquestBpEuLawDataAck_num_tag 20

/* Struct field encoding specification for nanopb */
#define pd335_bms_bp_BMSHeartBeatReport_FIELDLIST(X, a) \
X(a, STATIC,   OPTIONAL, UINT32,   num,               1) \
X(a, STATIC,   OPTIONAL, UINT32,   type,              2) \
X(a, STATIC,   OPTIONAL, UINT32,   cell_id,           3) \
X(a, STATIC,   OPTIONAL, UINT32,   err_code,          4) \
X(a, STATIC,   OPTIONAL, UINT32,   sys_ver,           5) \
X(a, STATIC,   OPTIONAL, UINT32,   soc,               6) \
X(a, STATIC,   OPTIONAL, UINT32,   vol,               7) \
X(a, STATIC,   OPTIONAL, INT32,    amp,               8) \
X(a, STATIC,   OPTIONAL, INT32,    temp,              9) \
X(a, STATIC,   OPTIONAL, UINT32,   open_bms_flag,    10) \
X(a, STATIC,   OPTIONAL, UINT32,   design_cap,       11) \
X(a, STATIC,   OPTIONAL, UINT32,   remain_cap,       12) \
X(a, STATIC,   OPTIONAL, UINT32,   full_cap,         13) \
X(a, STATIC,   OPTIONAL, UINT32,   cycles,           14) \
X(a, STATIC,   OPTIONAL, UINT32,   soh,              15) \
X(a, STATIC,   OPTIONAL, UINT32,   max_cell_vol,     16) \
X(a, STATIC,   OPTIONAL, UINT32,   min_cell_vol,     17) \
X(a, STATIC,   OPTIONAL, INT32,    max_cell_temp,    18) \
X(a, STATIC,   OPTIONAL, INT32,    min_cell_temp,    19) \
X(a, STATIC,   OPTIONAL, INT32,    max_mos_temp,     20) \
X(a, STATIC,   OPTIONAL, INT32,    min_mos_temp,     21) \
X(a, STATIC,   OPTIONAL, UINT32,   bms_fault,        22) \
X(a, STATIC,   OPTIONAL, UINT32,   bq_sys_stat_reg,  23) \
X(a, STATIC,   OPTIONAL, UINT32,   tag_chg_amp,      24) \
X(a, STATIC,   OPTIONAL, FLOAT,    f32_show_soc,     25) \
X(a, STATIC,   OPTIONAL, UINT32,   input_watts,      26) \
X(a, STATIC,   OPTIONAL, UINT32,   output_watts,     27) \
X(a, STATIC,   OPTIONAL, UINT32,   remain_time,      28) \
X(a, STATIC,   OPTIONAL, UINT32,   mos_state,        29) \
X(a, STATIC,   OPTIONAL, UINT32,   balance_state,    30) \
X(a, STATIC,   OPTIONAL, UINT32,   max_vol_diff,     31) \
X(a, STATIC,   OPTIONAL, UINT32,   cell_series_num,  32) \
X(a, CALLBACK, REPEATED, UINT32,   cell_vol,         33) \
X(a, STATIC,   OPTIONAL, UINT32,   cell_ntc_num,     34) \
X(a, CALLBACK, REPEATED, INT32,    cell_temp,        35) \
X(a, CALLBACK, OPTIONAL, STRING,   hw_ver,           36) \
X(a, STATIC,   OPTIONAL, UINT32,   bms_heartbeat_ver,  37) \
X(a, STATIC,   OPTIONAL, UINT32,   ecloud_ocv,       38) \
X(a, CALLBACK, OPTIONAL, STRING,   bms_sn,           39) \
X(a, STATIC,   OPTIONAL, UINT32,   product_type,     40) \
X(a, STATIC,   OPTIONAL, UINT32,   product_detail,   41) \
X(a, STATIC,   OPTIONAL, FLOAT,    act_soc,          42) \
X(a, STATIC,   OPTIONAL, FLOAT,    diff_soc,         43) \
X(a, STATIC,   OPTIONAL, FLOAT,    target_soc,       44) \
X(a, STATIC,   OPTIONAL, UINT32,   sys_loader_ver,   45) \
X(a, STATIC,   OPTIONAL, UINT32,   sys_state,        46) \
X(a, STATIC,   OPTIONAL, UINT32,   chg_dsg_state,    47) \
X(a, STATIC,   OPTIONAL, UINT32,   all_err_code,     48) \
X(a, STATIC,   OPTIONAL, UINT32,   all_bms_fault,    49) \
X(a, STATIC,   OPTIONAL, UINT32,   accu_chg_cap,     50) \
X(a, STATIC,   OPTIONAL, UINT32,   accu_dsg_cap,     51) \
X(a, STATIC,   OPTIONAL, FLOAT,    real_soh,         52) \
X(a, STATIC,   OPTIONAL, FLOAT,    calendar_soh,     53) \
X(a, STATIC,   OPTIONAL, FLOAT,    cycle_soh,        54) \
X(a, STATIC,   OPTIONAL, UINT32,   mos_ntc_num,      55) \
X(a, CALLBACK, REPEATED, INT32,    mos_temp,         56) \
X(a, STATIC,   OPTIONAL, UINT32,   env_ntc_num,      57) \
X(a, CALLBACK, REPEATED, INT32,    env_temp,         58) \
X(a, STATIC,   OPTIONAL, UINT32,   heatfilm_ntc_num,  59) \
X(a, CALLBACK, REPEATED, INT32,    heatfilm_temp,    60) \
X(a, STATIC,   OPTIONAL, UINT32,   cur_sensor_ntc_num,  61) \
X(a, CALLBACK, REPEATED, INT32,    cur_sensor_temp,  62) \
X(a, STATIC,   OPTIONAL, INT32,    max_env_temp,     63) \
X(a, STATIC,   OPTIONAL, INT32,    min_env_temp,     64) \
X(a, STATIC,   OPTIONAL, INT32,    max_heatfilm_temp,  65) \
X(a, STATIC,   OPTIONAL, INT32,    min_heatfilm_temp,  66) \
X(a, STATIC,   OPTIONAL, INT32,    max_cur_sensor_temp,  67) \
X(a, STATIC,   OPTIONAL, INT32,    min_cur_sensor_temp,  68) \
X(a, STATIC,   OPTIONAL, UINT32,   balance_cmd,      69) \
X(a, CALLBACK, REPEATED, UINT32,   remain_balance_time,  70) \
X(a, STATIC,   OPTIONAL, UINT32,   afe_sys_status,   71) \
X(a, STATIC,   OPTIONAL, UINT32,   mcu_pin_in_status,  72) \
X(a, STATIC,   OPTIONAL, UINT32,   mcu_pin_out_status,  73) \
X(a, STATIC,   OPTIONAL, UINT32,   bms_alarm_state1,  74) \
X(a, STATIC,   OPTIONAL, UINT32,   bms_alarm_state2,  75) \
X(a, STATIC,   OPTIONAL, UINT32,   bms_protect_state1,  76) \
X(a, STATIC,   OPTIONAL, UINT32,   bms_protect_state2,  77) \
X(a, STATIC,   OPTIONAL, UINT32,   bms_fault_state,  78) \
X(a, STATIC,   OPTIONAL, UINT32,   accu_chg_energy,  79) \
X(a, STATIC,   OPTIONAL, UINT32,   accu_dsg_energy,  80) \
X(a, CALLBACK, OPTIONAL, STRING,   pack_sn,          81) \
X(a, STATIC,   OPTIONAL, UINT32,   water_in_flag,    82)
#define pd335_bms_bp_BMSHeartBeatReport_CALLBACK pb_default_field_callback
#define pd335_bms_bp_BMSHeartBeatReport_DEFAULT NULL

#define pd335_bms_bp_ems_heartbeat_pack_v1p0_t_FIELDLIST(X, a) \
X(a, STATIC,   OPTIONAL, UINT32,   chg_state,         1) \
X(a, STATIC,   OPTIONAL, UINT32,   chg_cmd,           2) \
X(a, STATIC,   OPTIONAL, UINT32,   dsg_cmd,           3) \
X(a, STATIC,   OPTIONAL, UINT32,   chg_vol,           4) \
X(a, STATIC,   OPTIONAL, UINT32,   chg_amp,           5) \
X(a, STATIC,   OPTIONAL, UINT32,   fan_level,         6) \
X(a, STATIC,   OPTIONAL, UINT32,   max_charge_soc,    7) \
X(a, STATIC,   OPTIONAL, UINT32,   bms_model,         8) \
X(a, STATIC,   OPTIONAL, UINT32,   lcd_show_soc,      9) \
X(a, STATIC,   OPTIONAL, UINT32,   open_ups_flag,    10) \
X(a, STATIC,   OPTIONAL, UINT32,   bms_warning_state,  11) \
X(a, STATIC,   OPTIONAL, UINT32,   chg_remain_time,  12) \
X(a, STATIC,   OPTIONAL, UINT32,   dsg_remain_time,  13) \
X(a, STATIC,   OPTIONAL, UINT32,   ems_is_normal_flag,  14) \
X(a, STATIC,   OPTIONAL, FLOAT,    f32_lcd_show_soc,  15) \
X(a, CALLBACK, REPEATED, UINT32,   bms_is_connt,     16) \
X(a, STATIC,   OPTIONAL, UINT32,   max_available_num,  17) \
X(a, STATIC,   OPTIONAL, UINT32,   open_bms_idx,     18) \
X(a, STATIC,   OPTIONAL, UINT32,   para_vol_min,     19) \
X(a, STATIC,   OPTIONAL, UINT32,   para_vol_max,     20) \
X(a, STATIC,   OPTIONAL, UINT32,   min_dsg_soc,      21) \
X(a, STATIC,   OPTIONAL, UINT32,   min_open_oil_eb_soc,  22) \
X(a, STATIC,   OPTIONAL, UINT32,   max_close_oil_eb_soc,  23)
#define pd335_bms_bp_ems_heartbeat_pack_v1p0_t_CALLBACK pb_default_field_callback
#define pd335_bms_bp_ems_heartbeat_pack_v1p0_t_DEFAULT NULL

#define pd335_bms_bp_ems_heartbeat_pack_v1p3_t_FIELDLIST(X, a) \
X(a, STATIC,   OPTIONAL, UINT32,   chg_disable_cond,   1) \
X(a, STATIC,   OPTIONAL, UINT32,   dsg_disable_cond,   2) \
X(a, STATIC,   OPTIONAL, UINT32,   chg_line_plug_in_flag,   3) \
X(a, STATIC,   OPTIONAL, UINT32,   sys_chg_dsg_state,   4) \
X(a, STATIC,   OPTIONAL, UINT32,   ems_heartbeat_ver,   5)
#define pd335_bms_bp_ems_heartbeat_pack_v1p3_t_CALLBACK NULL
#define pd335_bms_bp_ems_heartbeat_pack_v1p3_t_DEFAULT NULL

#define pd335_bms_bp_CMSHeartBeatReport_FIELDLIST(X, a) \
X(a, STATIC,   OPTIONAL, MESSAGE,  v1p0,              1) \
X(a, STATIC,   OPTIONAL, MESSAGE,  v1p3,              2)
#define pd335_bms_bp_CMSHeartBeatReport_CALLBACK NULL
#define pd335_bms_bp_CMSHeartBeatReport_DEFAULT NULL
#define pd335_bms_bp_CMSHeartBeatReport_v1p0_MSGTYPE pd335_bms_bp_ems_heartbeat_pack_v1p0_t
#define pd335_bms_bp_CMSHeartBeatReport_v1p3_MSGTYPE pd335_bms_bp_ems_heartbeat_pack_v1p3_t

#define pd335_bms_bp_AppRuquestBpEuLawData_FIELDLIST(X, a) \
X(a, CALLBACK, OPTIONAL, STRING,   pack_sn,           1) \
X(a, STATIC,   OPTIONAL, UINT32,   app_to_bms_launch_date,   2) \
X(a, STATIC,   OPTIONAL, UINT32,   app_launch_date_set_type,   3) \
X(a, STATIC,   OPTIONAL, UINT32,   app_to_bms_reset_flag,   4) \
X(a, STATIC,   OPTIONAL, UINT32,   bms_data_upload_en,   5)
#define pd335_bms_bp_AppRuquestBpEuLawData_CALLBACK pb_default_field_callback
#define pd335_bms_bp_AppRuquestBpEuLawData_DEFAULT NULL

#define pd335_bms_bp_AppRuquestBpEuLawDataAck_FIELDLIST(X, a) \
X(a, CALLBACK, OPTIONAL, STRING,   bms_sn,            1) \
X(a, STATIC,   OPTIONAL, UINT32,   soh,               2) \
X(a, STATIC,   OPTIONAL, UINT32,   accu_chg_cap,      3) \
X(a, STATIC,   OPTIONAL, UINT32,   accu_dsg_cap,      4) \
X(a, STATIC,   OPTIONAL, UINT32,   accu_chg_energy,   5) \
X(a, STATIC,   OPTIONAL, UINT32,   accu_dsg_energy,   6) \
X(a, STATIC,   OPTIONAL, UINT32,   deep_dsg_cnt,      7) \
X(a, STATIC,   OPTIONAL, UINT32,   high_temp_use_time,   8) \
X(a, STATIC,   OPTIONAL, UINT32,   low_temp_use_time,   9) \
X(a, STATIC,   OPTIONAL, UINT32,   high_temp_chg_time,  10) \
X(a, STATIC,   OPTIONAL, UINT32,   low_temp_chg_time,  11) \
X(a, STATIC,   OPTIONAL, UINT32,   bp_launch_date,   12) \
X(a, STATIC,   OPTIONAL, UINT32,   bp_cycles,        13) \
X(a, STATIC,   OPTIONAL, FLOAT,    bp_power_capability,  14) \
X(a, STATIC,   OPTIONAL, FLOAT,    bp_round_trip_eff,  15) \
X(a, STATIC,   OPTIONAL, FLOAT,    bp_self_dsg_rate,  16) \
X(a, STATIC,   OPTIONAL, FLOAT,    bp_ohm_res,       17) \
X(a, STATIC,   OPTIONAL, UENUM,    bp_reset_flag,    18) \
X(a, STATIC,   OPTIONAL, UENUM,    bp_launch_date_flag,  19) \
X(a, STATIC,   OPTIONAL, UINT32,   num,              20)
#define pd335_bms_bp_AppRuquestBpEuLawDataAck_CALLBACK pb_default_field_callback
#define pd335_bms_bp_AppRuquestBpEuLawDataAck_DEFAULT NULL

extern const pb_msgdesc_t pd335_bms_bp_BMSHeartBeatReport_msg;
extern const pb_msgdesc_t pd335_bms_bp_ems_heartbeat_pack_v1p0_t_msg;
extern const pb_msgdesc_t pd335_bms_bp_ems_heartbeat_pack_v1p3_t_msg;
extern const pb_msgdesc_t pd335_bms_bp_CMSHeartBeatReport_msg;
extern const pb_msgdesc_t pd335_bms_bp_AppRuquestBpEuLawData_msg;
extern const pb_msgdesc_t pd335_bms_bp_AppRuquestBpEuLawDataAck_msg;

/* Defines for backwards compatibility with code written before nanopb-0.4.0 */
#define pd335_bms_bp_BMSHeartBeatReport_fields &pd335_bms_bp_BMSHeartBeatReport_msg
#define pd335_bms_bp_ems_heartbeat_pack_v1p0_t_fields &pd335_bms_bp_ems_heartbeat_pack_v1p0_t_msg
#define pd335_bms_bp_ems_heartbeat_pack_v1p3_t_fields &pd335_bms_bp_ems_heartbeat_pack_v1p3_t_msg
#define pd335_bms_bp_CMSHeartBeatReport_fields &pd335_bms_bp_CMSHeartBeatReport_msg
#define pd335_bms_bp_AppRuquestBpEuLawData_fields &pd335_bms_bp_AppRuquestBpEuLawData_msg
#define pd335_bms_bp_AppRuquestBpEuLawDataAck_fields &pd335_bms_bp_AppRuquestBpEuLawDataAck_msg

/* Maximum encoded size of messages (where known) */
/* pd335_bms_bp_BMSHeartBeatReport_size depends on runtime parameters */
/* pd335_bms_bp_ems_heartbeat_pack_v1p0_t_size depends on runtime parameters */
/* pd335_bms_bp_CMSHeartBeatReport_size depends on runtime parameters */
/* pd335_bms_bp_AppRuquestBpEuLawData_size depends on runtime parameters */
/* pd335_bms_bp_AppRuquestBpEuLawDataAck_size depends on runtime parameters */
#define PD335_BMS_BP_PYTHON_IMPLEMENTATION_PROTO_PD335_BMS_BP_PB_H_MAX_SIZE pd335_bms_bp_ems_heartbeat_pack_v1p3_t_size
#define pd335_bms_bp_ems_heartbeat_pack_v1p3_t_size 30

#ifdef __cplusplus
} /* extern "C" */
#endif

#endif
