/* Automatically generated nanopb constant definitions */
/* Generated by nanopb-0.4.9.1 */

#include "utc_sys.pb.h"
#if PB_PROTO_HEADER_VERSION != 40
#error Regenerate this file with the current version of nanopb generator.
#endif

PB_BIND(utc_APPParaHeartbeatReport, utc_APPParaHeartbeatReport, AUTO)


PB_BIND(utc_SysUTCRequest, utc_SysUTCRequest, AUTO)


PB_BIND(utc_SysUTCRequestACK, utc_SysUTCRequestACK, AUTO)


PB_BIND(utc_SysRTCInfoGet, utc_SysRTCInfoGet, AUTO)


PB_BIND(utc_SysRTCInfoGetACK, utc_SysRTCInfoGetACK, AUTO)


PB_BIND(utc_SysUTCSync, utc_SysUTCSync, AUTO)


PB_BIND(utc_SetCmdResultAck, utc_SetCmdResultAck, AUTO)


PB_BIND(utc_SysTimezoneSync, utc_SysTimezoneSync, AUTO)


PB_BIND(utc_SysTimezoneIDSync, utc_SysTimezoneIDSync, AUTO)
