/* Automatically generated nanopb header */
/* Generated by nanopb-0.4.9.1 */

#ifndef PB_UTC_SYS_PB_H_INCLUDED
#define PB_UTC_SYS_PB_H_INCLUDED
#include "pb.h"

#if PB_PROTO_HEADER_VERSION != 40
#error Regenerate this file with the current version of nanopb generator.
#endif

/* Struct definitions */
typedef struct _utc_APPParaHeartbeatReport {
    int32_t sys_timezone;
    pb_callback_t sys_timezone_id;
} utc_APPParaHeartbeatReport;

typedef struct _utc_SysUTCRequest {
    char dummy_field;
} utc_SysUTCRequest;

typedef struct _utc_SysUTCRequestACK {
    uint32_t sys_utc_time;
} utc_SysUTCRequestACK;

typedef struct _utc_SysRTCInfoGet {
    char dummy_field;
} utc_SysRTCInfoGet;

typedef struct _utc_SysRTCInfoGetACK {
    uint32_t sys_utc_time;
    int32_t sys_timezone;
    uint32_t time_type;
    pb_callback_t timezone_id;
} utc_SysRTCInfoGetACK;

typedef struct _utc_SysUTCSync {
    uint32_t sys_utc_time;
} utc_SysUTCSync;

typedef struct _utc_SetCmdResultAck {
    int32_t result;
} utc_SetCmdResultAck;

typedef struct _utc_SysTimezoneSync {
    int32_t sys_timezone;
} utc_SysTimezoneSync;

typedef struct _utc_SysTimezoneIDSync {
    pb_callback_t timezone_id;
} utc_SysTimezoneIDSync;


#ifdef __cplusplus
extern "C" {
#endif

/* Initializer values for message structs */
#define utc_APPParaHeartbeatReport_init_default  {0, {{NULL}, NULL}}
#define utc_SysUTCRequest_init_default           {0}
#define utc_SysUTCRequestACK_init_default        {0}
#define utc_SysRTCInfoGet_init_default           {0}
#define utc_SysRTCInfoGetACK_init_default        {0, 0, 0, {{NULL}, NULL}}
#define utc_SysUTCSync_init_default              {0}
#define utc_SetCmdResultAck_init_default         {0}
#define utc_SysTimezoneSync_init_default         {0}
#define utc_SysTimezoneIDSync_init_default       {{{NULL}, NULL}}
#define utc_APPParaHeartbeatReport_init_zero     {0, {{NULL}, NULL}}
#define utc_SysUTCRequest_init_zero              {0}
#define utc_SysUTCRequestACK_init_zero           {0}
#define utc_SysRTCInfoGet_init_zero              {0}
#define utc_SysRTCInfoGetACK_init_zero           {0, 0, 0, {{NULL}, NULL}}
#define utc_SysUTCSync_init_zero                 {0}
#define utc_SetCmdResultAck_init_zero            {0}
#define utc_SysTimezoneSync_init_zero            {0}
#define utc_SysTimezoneIDSync_init_zero          {{{NULL}, NULL}}

/* Field tags (for use in manual encoding/decoding) */
#define utc_APPParaHeartbeatReport_sys_timezone_tag 20
#define utc_APPParaHeartbeatReport_sys_timezone_id_tag 21
#define utc_SysUTCRequestACK_sys_utc_time_tag    1
#define utc_SysRTCInfoGetACK_sys_utc_time_tag    1
#define utc_SysRTCInfoGetACK_sys_timezone_tag    2
#define utc_SysRTCInfoGetACK_time_type_tag       3
#define utc_SysRTCInfoGetACK_timezone_id_tag     4
#define utc_SysUTCSync_sys_utc_time_tag          1
#define utc_SetCmdResultAck_result_tag           1
#define utc_SysTimezoneSync_sys_timezone_tag     1
#define utc_SysTimezoneIDSync_timezone_id_tag    1

/* Struct field encoding specification for nanopb */
#define utc_APPParaHeartbeatReport_FIELDLIST(X, a) \
X(a, STATIC,   SINGULAR, SINT32,   sys_timezone,     20) \
X(a, CALLBACK, SINGULAR, STRING,   sys_timezone_id,  21)
#define utc_APPParaHeartbeatReport_CALLBACK pb_default_field_callback
#define utc_APPParaHeartbeatReport_DEFAULT NULL

#define utc_SysUTCRequest_FIELDLIST(X, a) \

#define utc_SysUTCRequest_CALLBACK NULL
#define utc_SysUTCRequest_DEFAULT NULL

#define utc_SysUTCRequestACK_FIELDLIST(X, a) \
X(a, STATIC,   SINGULAR, UINT32,   sys_utc_time,      1)
#define utc_SysUTCRequestACK_CALLBACK NULL
#define utc_SysUTCRequestACK_DEFAULT NULL

#define utc_SysRTCInfoGet_FIELDLIST(X, a) \

#define utc_SysRTCInfoGet_CALLBACK NULL
#define utc_SysRTCInfoGet_DEFAULT NULL

#define utc_SysRTCInfoGetACK_FIELDLIST(X, a) \
X(a, STATIC,   SINGULAR, UINT32,   sys_utc_time,      1) \
X(a, STATIC,   SINGULAR, SINT32,   sys_timezone,      2) \
X(a, STATIC,   SINGULAR, UINT32,   time_type,         3) \
X(a, CALLBACK, SINGULAR, STRING,   timezone_id,       4)
#define utc_SysRTCInfoGetACK_CALLBACK pb_default_field_callback
#define utc_SysRTCInfoGetACK_DEFAULT NULL

#define utc_SysUTCSync_FIELDLIST(X, a) \
X(a, STATIC,   SINGULAR, UINT32,   sys_utc_time,      1)
#define utc_SysUTCSync_CALLBACK NULL
#define utc_SysUTCSync_DEFAULT NULL

#define utc_SetCmdResultAck_FIELDLIST(X, a) \
X(a, STATIC,   SINGULAR, SINT32,   result,            1)
#define utc_SetCmdResultAck_CALLBACK NULL
#define utc_SetCmdResultAck_DEFAULT NULL

#define utc_SysTimezoneSync_FIELDLIST(X, a) \
X(a, STATIC,   SINGULAR, SINT32,   sys_timezone,      1)
#define utc_SysTimezoneSync_CALLBACK NULL
#define utc_SysTimezoneSync_DEFAULT NULL

#define utc_SysTimezoneIDSync_FIELDLIST(X, a) \
X(a, CALLBACK, SINGULAR, STRING,   timezone_id,       1)
#define utc_SysTimezoneIDSync_CALLBACK pb_default_field_callback
#define utc_SysTimezoneIDSync_DEFAULT NULL

extern const pb_msgdesc_t utc_APPParaHeartbeatReport_msg;
extern const pb_msgdesc_t utc_SysUTCRequest_msg;
extern const pb_msgdesc_t utc_SysUTCRequestACK_msg;
extern const pb_msgdesc_t utc_SysRTCInfoGet_msg;
extern const pb_msgdesc_t utc_SysRTCInfoGetACK_msg;
extern const pb_msgdesc_t utc_SysUTCSync_msg;
extern const pb_msgdesc_t utc_SetCmdResultAck_msg;
extern const pb_msgdesc_t utc_SysTimezoneSync_msg;
extern const pb_msgdesc_t utc_SysTimezoneIDSync_msg;

/* Defines for backwards compatibility with code written before nanopb-0.4.0 */
#define utc_APPParaHeartbeatReport_fields &utc_APPParaHeartbeatReport_msg
#define utc_SysUTCRequest_fields &utc_SysUTCRequest_msg
#define utc_SysUTCRequestACK_fields &utc_SysUTCRequestACK_msg
#define utc_SysRTCInfoGet_fields &utc_SysRTCInfoGet_msg
#define utc_SysRTCInfoGetACK_fields &utc_SysRTCInfoGetACK_msg
#define utc_SysUTCSync_fields &utc_SysUTCSync_msg
#define utc_SetCmdResultAck_fields &utc_SetCmdResultAck_msg
#define utc_SysTimezoneSync_fields &utc_SysTimezoneSync_msg
#define utc_SysTimezoneIDSync_fields &utc_SysTimezoneIDSync_msg

/* Maximum encoded size of messages (where known) */
/* utc_APPParaHeartbeatReport_size depends on runtime parameters */
/* utc_SysRTCInfoGetACK_size depends on runtime parameters */
/* utc_SysTimezoneIDSync_size depends on runtime parameters */
#define UTC_ECOFLOWESP32_PROTO_UTC_SYS_PB_H_MAX_SIZE utc_SysUTCRequestACK_size
#define utc_SetCmdResultAck_size                 6
#define utc_SysRTCInfoGet_size                   0
#define utc_SysTimezoneSync_size                 6
#define utc_SysUTCRequestACK_size                6
#define utc_SysUTCRequest_size                   0
#define utc_SysUTCSync_size                      6

#ifdef __cplusplus
} /* extern "C" */
#endif

#endif
