/* Automatically generated nanopb header */
/* Generated by nanopb-0.4.9.1 */

#ifndef PB_PROTO_BMS_DELTA_PB_H_INCLUDED
#define PB_PROTO_BMS_DELTA_PB_H_INCLUDED
#include <pb.h>

#if PB_PROTO_HEADER_VERSION != 40
#error Regenerate this file with the current version of nanopb generator.
#endif

/* Struct definitions */
typedef struct _BmsDelta_Message_Params {
    uint32_t bms_fault;
    uint32_t soc;
    uint32_t version;
    uint32_t remain_cap;
    uint32_t vol;
    uint32_t cur;
    uint32_t temp;
    uint32_t max_cell_vol;
    uint32_t min_cell_vol;
    uint32_t max_cell_temp;
    uint32_t min_cell_temp;
    uint32_t max_mos_temp;
    uint32_t min_mos_temp;
} BmsDelta_Message_Params;

typedef struct _BmsDelta_Message {
    bool has_params;
    BmsDelta_Message_Params params;
} BmsDelta_Message;

typedef struct _BmsDelta {
    bool has_message;
    BmsDelta_Message message;
} BmsDelta;


#ifdef __cplusplus
extern "C" {
#endif

/* Initializer values for message structs */
#define BmsDelta_init_default                    {false, BmsDelta_Message_init_default}
#define BmsDelta_Message_init_default            {false, BmsDelta_Message_Params_init_default}
#define BmsDelta_Message_Params_init_default     {0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0}
#define BmsDelta_init_zero                       {false, BmsDelta_Message_init_zero}
#define BmsDelta_Message_init_zero               {false, BmsDelta_Message_Params_init_zero}
#define BmsDelta_Message_Params_init_zero        {0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0}

/* Field tags (for use in manual encoding/decoding) */
#define BmsDelta_Message_Params_bms_fault_tag    1
#define BmsDelta_Message_Params_soc_tag          2
#define BmsDelta_Message_Params_version_tag      3
#define BmsDelta_Message_Params_remain_cap_tag   4
#define BmsDelta_Message_Params_vol_tag          5
#define BmsDelta_Message_Params_cur_tag          6
#define BmsDelta_Message_Params_temp_tag         7
#define BmsDelta_Message_Params_max_cell_vol_tag 8
#define BmsDelta_Message_Params_min_cell_vol_tag 9
#define BmsDelta_Message_Params_max_cell_temp_tag 10
#define BmsDelta_Message_Params_min_cell_temp_tag 11
#define BmsDelta_Message_Params_max_mos_temp_tag 12
#define BmsDelta_Message_Params_min_mos_temp_tag 13
#define BmsDelta_Message_params_tag              1
#define BmsDelta_message_tag                     1

/* Struct field encoding specification for nanopb */
#define BmsDelta_FIELDLIST(X, a) \
X(a, STATIC,   OPTIONAL, MESSAGE,  message,           1)
#define BmsDelta_CALLBACK NULL
#define BmsDelta_DEFAULT NULL
#define BmsDelta_message_MSGTYPE BmsDelta_Message

#define BmsDelta_Message_FIELDLIST(X, a) \
X(a, STATIC,   OPTIONAL, MESSAGE,  params,            1)
#define BmsDelta_Message_CALLBACK NULL
#define BmsDelta_Message_DEFAULT NULL
#define BmsDelta_Message_params_MSGTYPE BmsDelta_Message_Params

#define BmsDelta_Message_Params_FIELDLIST(X, a) \
X(a, STATIC,   SINGULAR, UINT32,   bms_fault,         1) \
X(a, STATIC,   SINGULAR, UINT32,   soc,               2) \
X(a, STATIC,   SINGULAR, UINT32,   version,           3) \
X(a, STATIC,   SINGULAR, UINT32,   remain_cap,        4) \
X(a, STATIC,   SINGULAR, UINT32,   vol,               5) \
X(a, STATIC,   SINGULAR, UINT32,   cur,               6) \
X(a, STATIC,   SINGULAR, UINT32,   temp,              7) \
X(a, STATIC,   SINGULAR, UINT32,   max_cell_vol,      8) \
X(a, STATIC,   SINGULAR, UINT32,   min_cell_vol,      9) \
X(a, STATIC,   SINGULAR, UINT32,   max_cell_temp,    10) \
X(a, STATIC,   SINGULAR, UINT32,   min_cell_temp,    11) \
X(a, STATIC,   SINGULAR, UINT32,   max_mos_temp,     12) \
X(a, STATIC,   SINGULAR, UINT32,   min_mos_temp,     13)
#define BmsDelta_Message_Params_CALLBACK NULL
#define BmsDelta_Message_Params_DEFAULT NULL

extern const pb_msgdesc_t BmsDelta_msg;
extern const pb_msgdesc_t BmsDelta_Message_msg;
extern const pb_msgdesc_t BmsDelta_Message_Params_msg;

/* Defines for backwards compatibility with code written before nanopb-0.4.0 */
#define BmsDelta_fields &BmsDelta_msg
#define BmsDelta_Message_fields &BmsDelta_Message_msg
#define BmsDelta_Message_Params_fields &BmsDelta_Message_Params_msg

/* Maximum encoded size of messages (where known) */
#define BmsDelta_Message_Params_size             78
#define BmsDelta_Message_size                    80
#define BmsDelta_size                            82
#define PROTO_BMS_DELTA_PB_H_MAX_SIZE            BmsDelta_size

#ifdef __cplusplus
} /* extern "C" */
#endif

#endif
