/* Automatically generated nanopb constant definitions */
/* Generated by nanopb-0.4.9.1 */

#include "proto/bms_delta.pb.h"
#if PB_PROTO_HEADER_VERSION != 40
#error Regenerate this file with the current version of nanopb generator.
#endif

PB_BIND(BmsDelta, BmsDelta, AUTO)


PB_BIND(BmsDelta_Message, BmsDelta_Message, AUTO)


PB_BIND(BmsDelta_Message_Params, BmsDelta_Message_Params, AUTO)
