/* Automatically generated nanopb constant definitions */
/* Generated by nanopb-0.4.9.1 */

#include "proto/ems_delta.pb.h"
#if PB_PROTO_HEADER_VERSION != 40
#error Regenerate this file with the current version of nanopb generator.
#endif

PB_BIND(EmsDelta, EmsDelta, AUTO)


PB_BIND(EmsDelta_Message, EmsDelta_Message, AUTO)


PB_BIND(EmsDelta_Message_Params, EmsDelta_Message_Params, AUTO)
