/* Automatically generated nanopb header */
/* Generated by nanopb-0.4.9.1 */

#ifndef PB_PROTO_EMS_DELTA_PB_H_INCLUDED
#define PB_PROTO_EMS_DELTA_PB_H_INCLUDED
#include <pb.h>

#if PB_PROTO_HEADER_VERSION != 40
#error Regenerate this file with the current version of nanopb generator.
#endif

/* Struct definitions */
typedef struct _EmsDelta_Message_Params {
    uint32_t chg_remain;
    uint32_t dsg_remain;
    uint32_t chg_state;
    bool smart_chg_switch;
    uint32_t chg_cur;
    uint32_t chg_vol;
    uint32_t chg_temp;
    uint32_t input_watts;
    uint32_t output_watts;
} EmsDelta_Message_Params;

typedef struct _EmsDelta_Message {
    bool has_params;
    EmsDelta_Message_Params params;
} EmsDelta_Message;

typedef struct _EmsDelta {
    bool has_message;
    EmsDelta_Message message;
} EmsDelta;


#ifdef __cplusplus
extern "C" {
#endif

/* Initializer values for message structs */
#define EmsDelta_init_default                    {false, EmsDelta_Message_init_default}
#define EmsDelta_Message_init_default            {false, EmsDelta_Message_Params_init_default}
#define EmsDelta_Message_Params_init_default     {0, 0, 0, 0, 0, 0, 0, 0, 0}
#define EmsDelta_init_zero                       {false, EmsDelta_Message_init_zero}
#define EmsDelta_Message_init_zero               {false, EmsDelta_Message_Params_init_zero}
#define EmsDelta_Message_Params_init_zero        {0, 0, 0, 0, 0, 0, 0, 0, 0}

/* Field tags (for use in manual encoding/decoding) */
#define EmsDelta_Message_Params_chg_remain_tag   1
#define EmsDelta_Message_Params_dsg_remain_tag   2
#define EmsDelta_Message_Params_chg_state_tag    3
#define EmsDelta_Message_Params_smart_chg_switch_tag 4
#define EmsDelta_Message_Params_chg_cur_tag      5
#define EmsDelta_Message_Params_chg_vol_tag      6
#define EmsDelta_Message_Params_chg_temp_tag     7
#define EmsDelta_Message_Params_input_watts_tag  8
#define EmsDelta_Message_Params_output_watts_tag 9
#define EmsDelta_Message_params_tag              1
#define EmsDelta_message_tag                     1

/* Struct field encoding specification for nanopb */
#define EmsDelta_FIELDLIST(X, a) \
X(a, STATIC,   OPTIONAL, MESSAGE,  message,           1)
#define EmsDelta_CALLBACK NULL
#define EmsDelta_DEFAULT NULL
#define EmsDelta_message_MSGTYPE EmsDelta_Message

#define EmsDelta_Message_FIELDLIST(X, a) \
X(a, STATIC,   OPTIONAL, MESSAGE,  params,            1)
#define EmsDelta_Message_CALLBACK NULL
#define EmsDelta_Message_DEFAULT NULL
#define EmsDelta_Message_params_MSGTYPE EmsDelta_Message_Params

#define EmsDelta_Message_Params_FIELDLIST(X, a) \
X(a, STATIC,   SINGULAR, UINT32,   chg_remain,        1) \
X(a, STATIC,   SINGULAR, UINT32,   dsg_remain,        2) \
X(a, STATIC,   SINGULAR, UINT32,   chg_state,         3) \
X(a, STATIC,   SINGULAR, BOOL,     smart_chg_switch,   4) \
X(a, STATIC,   SINGULAR, UINT32,   chg_cur,           5) \
X(a, STATIC,   SINGULAR, UINT32,   chg_vol,           6) \
X(a, STATIC,   SINGULAR, UINT32,   chg_temp,          7) \
X(a, STATIC,   SINGULAR, UINT32,   input_watts,       8) \
X(a, STATIC,   SINGULAR, UINT32,   output_watts,      9)
#define EmsDelta_Message_Params_CALLBACK NULL
#define EmsDelta_Message_Params_DEFAULT NULL

extern const pb_msgdesc_t EmsDelta_msg;
extern const pb_msgdesc_t EmsDelta_Message_msg;
extern const pb_msgdesc_t EmsDelta_Message_Params_msg;

/* Defines for backwards compatibility with code written before nanopb-0.4.0 */
#define EmsDelta_fields &EmsDelta_msg
#define EmsDelta_Message_fields &EmsDelta_Message_msg
#define EmsDelta_Message_Params_fields &EmsDelta_Message_Params_msg

/* Maximum encoded size of messages (where known) */
#define EmsDelta_Message_Params_size             50
#define EmsDelta_Message_size                    52
#define EmsDelta_size                            54
#define PROTO_EMS_DELTA_PB_H_MAX_SIZE            EmsDelta_size

#ifdef __cplusplus
} /* extern "C" */
#endif

#endif
