/* Automatically generated nanopb constant definitions */
/* Generated by nanopb-0.4.9.1 */

#include "proto/kit_info.pb.h"
#if PB_PROTO_HEADER_VERSION != 40
#error Regenerate this file with the current version of nanopb generator.
#endif

PB_BIND(KitInfo, KitInfo, AUTO)


PB_BIND(KitInfo_Message, KitInfo_Message, AUTO)


PB_BIND(KitInfo_Message_Params, KitInfo_Message_Params, AUTO)
