/* Automatically generated nanopb header */
/* Generated by nanopb-0.4.9.1 */

#ifndef PB_PROTO_KIT_INFO_PB_H_INCLUDED
#define PB_PROTO_KIT_INFO_PB_H_INCLUDED
#include <pb.h>

#if PB_PROTO_HEADER_VERSION != 40
#error Regenerate this file with the current version of nanopb generator.
#endif

/* Struct definitions */
typedef struct _KitInfo_Message_Params {
    pb_callback_t sn;
    pb_callback_t hw_version;
    pb_callback_t sw_version;
    pb_callback_t product_type;
    uint32_t port_num;
} KitInfo_Message_Params;

typedef struct _KitInfo_Message {
    bool has_params;
    KitInfo_Message_Params params;
} KitInfo_Message;

typedef struct _KitInfo {
    bool has_message;
    KitInfo_Message message;
} KitInfo;


#ifdef __cplusplus
extern "C" {
#endif

/* Initializer values for message structs */
#define KitInfo_init_default                     {false, KitInfo_Message_init_default}
#define KitInfo_Message_init_default             {false, KitInfo_Message_Params_init_default}
#define KitInfo_Message_Params_init_default      {{{NULL}, NULL}, {{NULL}, NULL}, {{NULL}, NULL}, {{NULL}, NULL}, 0}
#define KitInfo_init_zero                        {false, KitInfo_Message_init_zero}
#define KitInfo_Message_init_zero                {false, KitInfo_Message_Params_init_zero}
#define KitInfo_Message_Params_init_zero         {{{NULL}, NULL}, {{NULL}, NULL}, {{NULL}, NULL}, {{NULL}, NULL}, 0}

/* Field tags (for use in manual encoding/decoding) */
#define KitInfo_Message_Params_sn_tag            1
#define KitInfo_Message_Params_hw_version_tag    2
#define KitInfo_Message_Params_sw_version_tag    3
#define KitInfo_Message_Params_product_type_tag  4
#define KitInfo_Message_Params_port_num_tag      5
#define KitInfo_Message_params_tag               1
#define KitInfo_message_tag                      1

/* Struct field encoding specification for nanopb */
#define KitInfo_FIELDLIST(X, a) \
X(a, STATIC,   OPTIONAL, MESSAGE,  message,           1)
#define KitInfo_CALLBACK NULL
#define KitInfo_DEFAULT NULL
#define KitInfo_message_MSGTYPE KitInfo_Message

#define KitInfo_Message_FIELDLIST(X, a) \
X(a, STATIC,   OPTIONAL, MESSAGE,  params,            1)
#define KitInfo_Message_CALLBACK NULL
#define KitInfo_Message_DEFAULT NULL
#define KitInfo_Message_params_MSGTYPE KitInfo_Message_Params

#define KitInfo_Message_Params_FIELDLIST(X, a) \
X(a, CALLBACK, SINGULAR, STRING,   sn,                1) \
X(a, CALLBACK, SINGULAR, STRING,   hw_version,        2) \
X(a, CALLBACK, SINGULAR, STRING,   sw_version,        3) \
X(a, CALLBACK, SINGULAR, STRING,   product_type,      4) \
X(a, STATIC,   SINGULAR, UINT32,   port_num,          5)
#define KitInfo_Message_Params_CALLBACK pb_default_field_callback
#define KitInfo_Message_Params_DEFAULT NULL

extern const pb_msgdesc_t KitInfo_msg;
extern const pb_msgdesc_t KitInfo_Message_msg;
extern const pb_msgdesc_t KitInfo_Message_Params_msg;

/* Defines for backwards compatibility with code written before nanopb-0.4.0 */
#define KitInfo_fields &KitInfo_msg
#define KitInfo_Message_fields &KitInfo_Message_msg
#define KitInfo_Message_Params_fields &KitInfo_Message_Params_msg

/* Maximum encoded size of messages (where known) */
/* KitInfo_size depends on runtime parameters */
/* KitInfo_Message_size depends on runtime parameters */
/* KitInfo_Message_Params_size depends on runtime parameters */

#ifdef __cplusplus
} /* extern "C" */
#endif

#endif
