/* Automatically generated nanopb header */
/* Generated by nanopb-0.4.9.1 */

#ifndef PB_PROTO_MPPT_DELTA_PB_H_INCLUDED
#define PB_PROTO_MPPT_DELTA_PB_H_INCLUDED
#include <pb.h>

#if PB_PROTO_HEADER_VERSION != 40
#error Regenerate this file with the current version of nanopb generator.
#endif

/* Struct definitions */
typedef struct _MpptDelta_Message_Params {
    uint32_t chg_type;
    uint32_t in_watts;
    uint32_t vol;
    uint32_t cur;
    uint32_t chg_state;
    uint32_t pv_chg_priority;
    uint32_t chg_limit;
    uint32_t dsg_limit;
} MpptDelta_Message_Params;

typedef struct _MpptDelta_Message {
    bool has_params;
    MpptDelta_Message_Params params;
} MpptDelta_Message;

typedef struct _MpptDelta {
    bool has_message;
    MpptDelta_Message message;
} MpptDelta;


#ifdef __cplusplus
extern "C" {
#endif

/* Initializer values for message structs */
#define MpptDelta_init_default                   {false, MpptDelta_Message_init_default}
#define MpptDelta_Message_init_default           {false, MpptDelta_Message_Params_init_default}
#define MpptDelta_Message_Params_init_default    {0, 0, 0, 0, 0, 0, 0, 0}
#define MpptDelta_init_zero                      {false, MpptDelta_Message_init_zero}
#define MpptDelta_Message_init_zero              {false, MpptDelta_Message_Params_init_zero}
#define MpptDelta_Message_Params_init_zero       {0, 0, 0, 0, 0, 0, 0, 0}

/* Field tags (for use in manual encoding/decoding) */
#define MpptDelta_Message_Params_chg_type_tag    1
#define MpptDelta_Message_Params_in_watts_tag    2
#define MpptDelta_Message_Params_vol_tag         3
#define MpptDelta_Message_Params_cur_tag         4
#define MpptDelta_Message_Params_chg_state_tag   5
#define MpptDelta_Message_Params_pv_chg_priority_tag 6
#define MpptDelta_Message_Params_chg_limit_tag   7
#define MpptDelta_Message_Params_dsg_limit_tag   8
#define MpptDelta_Message_params_tag             1
#define MpptDelta_message_tag                    1

/* Struct field encoding specification for nanopb */
#define MpptDelta_FIELDLIST(X, a) \
X(a, STATIC,   OPTIONAL, MESSAGE,  message,           1)
#define MpptDelta_CALLBACK NULL
#define MpptDelta_DEFAULT NULL
#define MpptDelta_message_MSGTYPE MpptDelta_Message

#define MpptDelta_Message_FIELDLIST(X, a) \
X(a, STATIC,   OPTIONAL, MESSAGE,  params,            1)
#define MpptDelta_Message_CALLBACK NULL
#define MpptDelta_Message_DEFAULT NULL
#define MpptDelta_Message_params_MSGTYPE MpptDelta_Message_Params

#define MpptDelta_Message_Params_FIELDLIST(X, a) \
X(a, STATIC,   SINGULAR, UINT32,   chg_type,          1) \
X(a, STATIC,   SINGULAR, UINT32,   in_watts,          2) \
X(a, STATIC,   SINGULAR, UINT32,   vol,               3) \
X(a, STATIC,   SINGULAR, UINT32,   cur,               4) \
X(a, STATIC,   SINGULAR, UINT32,   chg_state,         5) \
X(a, STATIC,   SINGULAR, UINT32,   pv_chg_priority,   6) \
X(a, STATIC,   SINGULAR, UINT32,   chg_limit,         7) \
X(a, STATIC,   SINGULAR, UINT32,   dsg_limit,         8)
#define MpptDelta_Message_Params_CALLBACK NULL
#define MpptDelta_Message_Params_DEFAULT NULL

extern const pb_msgdesc_t MpptDelta_msg;
extern const pb_msgdesc_t MpptDelta_Message_msg;
extern const pb_msgdesc_t MpptDelta_Message_Params_msg;

/* Defines for backwards compatibility with code written before nanopb-0.4.0 */
#define MpptDelta_fields &MpptDelta_msg
#define MpptDelta_Message_fields &MpptDelta_Message_msg
#define MpptDelta_Message_Params_fields &MpptDelta_Message_Params_msg

/* Maximum encoded size of messages (where known) */
#define MpptDelta_Message_Params_size            48
#define MpptDelta_Message_size                   50
#define MpptDelta_size                           52
#define PROTO_MPPT_DELTA_PB_H_MAX_SIZE           MpptDelta_size

#ifdef __cplusplus
} /* extern "C" */
#endif

#endif
