/* Automatically generated nanopb constant definitions */
/* Generated by nanopb-0.4.9.1 */

#include "proto/mppt_direct.pb.h"
#if PB_PROTO_HEADER_VERSION != 40
#error Regenerate this file with the current version of nanopb generator.
#endif

PB_BIND(MpptDirect, MpptDirect, AUTO)


PB_BIND(MpptDirect_Message, MpptDirect_Message, AUTO)


PB_BIND(MpptDirect_Message_Params, MpptDirect_Message_Params, AUTO)
