/* Automatically generated nanopb header */
/* Generated by nanopb-0.4.9.1 */

#ifndef PB_PROTO_MPPT_DIRECT_PB_H_INCLUDED
#define PB_PROTO_MPPT_DIRECT_PB_H_INCLUDED
#include <pb.h>

#if PB_PROTO_HEADER_VERSION != 40
#error Regenerate this file with the current version of nanopb generator.
#endif

/* Struct definitions */
typedef struct _MpptDirect_Message_Params {
    uint32_t state;
    uint32_t in_vol;
    uint32_t in_cur;
    uint32_t in_watts;
    uint32_t out_vol;
    uint32_t out_cur;
    uint32_t out_watts;
    uint32_t out_tmp;
    uint32_t fault;
} MpptDirect_Message_Params;

typedef struct _MpptDirect_Message {
    bool has_params;
    MpptDirect_Message_Params params;
} MpptDirect_Message;

typedef struct _MpptDirect {
    bool has_message;
    MpptDirect_Message message;
} MpptDirect;


#ifdef __cplusplus
extern "C" {
#endif

/* Initializer values for message structs */
#define MpptDirect_init_default                  {false, MpptDirect_Message_init_default}
#define MpptDirect_Message_init_default          {false, MpptDirect_Message_Params_init_default}
#define MpptDirect_Message_Params_init_default   {0, 0, 0, 0, 0, 0, 0, 0, 0}
#define MpptDirect_init_zero                     {false, MpptDirect_Message_init_zero}
#define MpptDirect_Message_init_zero             {false, MpptDirect_Message_Params_init_zero}
#define MpptDirect_Message_Params_init_zero      {0, 0, 0, 0, 0, 0, 0, 0, 0}

/* Field tags (for use in manual encoding/decoding) */
#define MpptDirect_Message_Params_state_tag      1
#define MpptDirect_Message_Params_in_vol_tag     2
#define MpptDirect_Message_Params_in_cur_tag     3
#define MpptDirect_Message_Params_in_watts_tag   4
#define MpptDirect_Message_Params_out_vol_tag    5
#define MpptDirect_Message_Params_out_cur_tag    6
#define MpptDirect_Message_Params_out_watts_tag  7
#define MpptDirect_Message_Params_out_tmp_tag    8
#define MpptDirect_Message_Params_fault_tag      9
#define MpptDirect_Message_params_tag            1
#define MpptDirect_message_tag                   1

/* Struct field encoding specification for nanopb */
#define MpptDirect_FIELDLIST(X, a) \
X(a, STATIC,   OPTIONAL, MESSAGE,  message,           1)
#define MpptDirect_CALLBACK NULL
#define MpptDirect_DEFAULT NULL
#define MpptDirect_message_MSGTYPE MpptDirect_Message

#define MpptDirect_Message_FIELDLIST(X, a) \
X(a, STATIC,   OPTIONAL, MESSAGE,  params,            1)
#define MpptDirect_Message_CALLBACK NULL
#define MpptDirect_Message_DEFAULT NULL
#define MpptDirect_Message_params_MSGTYPE MpptDirect_Message_Params

#define MpptDirect_Message_Params_FIELDLIST(X, a) \
X(a, STATIC,   SINGULAR, UINT32,   state,             1) \
X(a, STATIC,   SINGULAR, UINT32,   in_vol,            2) \
X(a, STATIC,   SINGULAR, UINT32,   in_cur,            3) \
X(a, STATIC,   SINGULAR, UINT32,   in_watts,          4) \
X(a, STATIC,   SINGULAR, UINT32,   out_vol,           5) \
X(a, STATIC,   SINGULAR, UINT32,   out_cur,           6) \
X(a, STATIC,   SINGULAR, UINT32,   out_watts,         7) \
X(a, STATIC,   SINGULAR, UINT32,   out_tmp,           8) \
X(a, STATIC,   SINGULAR, UINT32,   fault,             9)
#define MpptDirect_Message_Params_CALLBACK NULL
#define MpptDirect_Message_Params_DEFAULT NULL

extern const pb_msgdesc_t MpptDirect_msg;
extern const pb_msgdesc_t MpptDirect_Message_msg;
extern const pb_msgdesc_t MpptDirect_Message_Params_msg;

/* Defines for backwards compatibility with code written before nanopb-0.4.0 */
#define MpptDirect_fields &MpptDirect_msg
#define MpptDirect_Message_fields &MpptDirect_Message_msg
#define MpptDirect_Message_Params_fields &MpptDirect_Message_Params_msg

/* Maximum encoded size of messages (where known) */
#define MpptDirect_Message_Params_size           54
#define MpptDirect_Message_size                  56
#define MpptDirect_size                          58
#define PROTO_MPPT_DIRECT_PB_H_MAX_SIZE          MpptDirect_size

#ifdef __cplusplus
} /* extern "C" */
#endif

#endif
