/* Automatically generated nanopb constant definitions */
/* Generated by nanopb-0.4.9.1 */

#include "proto/mppt_delta.pb.h"
#if PB_PROTO_HEADER_VERSION != 40
#error Regenerate this file with the current version of nanopb generator.
#endif

PB_BIND(MpptDelta, MpptDelta, AUTO)


PB_BIND(MpptDelta_Message, MpptDelta_Message, AUTO)


PB_BIND(MpptDelta_Message_Params, MpptDelta_Message_Params, AUTO)
