/* Automatically generated nanopb constant definitions */
/* Generated by nanopb-0.4.9.1 */

#include "proto/pd_delta.pb.h"
#if PB_PROTO_HEADER_VERSION != 40
#error Regenerate this file with the current version of nanopb generator.
#endif

PB_BIND(PdDelta, PdDelta, AUTO)


PB_BIND(PdDelta_Message, PdDelta_Message, AUTO)


PB_BIND(PdDelta_Message_Params, PdDelta_Message_Params, AUTO)
