/* Automatically generated nanopb header */
/* Generated by nanopb-0.4.9.1 */

#ifndef PB_PROTO_PD_DELTA_PB_H_INCLUDED
#define PB_PROTO_PD_DELTA_PB_H_INCLUDED
#include <pb.h>

#if PB_PROTO_HEADER_VERSION != 40
#error Regenerate this file with the current version of nanopb generator.
#endif

/* Struct definitions */
typedef struct _PdDelta_Message_Params {
    uint32_t xt60_in_watts;
    uint32_t xt60_out_watts;
    uint32_t car_out_watts;
    uint32_t ac_in_watts;
    uint32_t inv_out_watts;
    uint32_t pd_out_watts;
    uint32_t usb_qc_out_watts;
    uint32_t type_c_out_watts;
    uint32_t dc_in_watts;
    uint32_t dsg_remain;
    uint32_t chg_remain;
    uint32_t soc;
    uint32_t ac_out_state;
    uint32_t car_out_state;
    uint32_t inv_out_freq;
    uint32_t car_out_voltage;
    uint32_t inv_out_voltage;
    uint32_t ac_in_freq;
    uint32_t ac_in_voltage;
    bool beep_state;
    uint32_t usb_out_state;
    uint32_t type_c_out_state;
    uint32_t xt60_out_state;
    uint32_t chg_limit;
    uint32_t chg_type;
    uint32_t dsg_limit;
    uint32_t fan_state;
    uint32_t in_type;
    uint32_t err_code;
} PdDelta_Message_Params;

typedef struct _PdDelta_Message {
    bool has_params;
    PdDelta_Message_Params params;
} PdDelta_Message;

typedef struct _PdDelta {
    bool has_message;
    PdDelta_Message message;
} PdDelta;


#ifdef __cplusplus
extern "C" {
#endif

/* Initializer values for message structs */
#define PdDelta_init_default                     {false, PdDelta_Message_init_default}
#define PdDelta_Message_init_default             {false, PdDelta_Message_Params_init_default}
#define PdDelta_Message_Params_init_default      {0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0}
#define PdDelta_init_zero                        {false, PdDelta_Message_init_zero}
#define PdDelta_Message_init_zero                {false, PdDelta_Message_Params_init_zero}
#define PdDelta_Message_Params_init_zero         {0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0}

/* Field tags (for use in manual encoding/decoding) */
#define PdDelta_Message_Params_xt60_in_watts_tag 1
#define PdDelta_Message_Params_xt60_out_watts_tag 2
#define PdDelta_Message_Params_car_out_watts_tag 3
#define PdDelta_Message_Params_ac_in_watts_tag   4
#define PdDelta_Message_Params_inv_out_watts_tag 5
#define PdDelta_Message_Params_pd_out_watts_tag  6
#define PdDelta_Message_Params_usb_qc_out_watts_tag 7
#define PdDelta_Message_Params_type_c_out_watts_tag 8
#define PdDelta_Message_Params_dc_in_watts_tag   9
#define PdDelta_Message_Params_dsg_remain_tag    10
#define PdDelta_Message_Params_chg_remain_tag    11
#define PdDelta_Message_Params_soc_tag           12
#define PdDelta_Message_Params_ac_out_state_tag  13
#define PdDelta_Message_Params_car_out_state_tag 14
#define PdDelta_Message_Params_inv_out_freq_tag  15
#define PdDelta_Message_Params_car_out_voltage_tag 16
#define PdDelta_Message_Params_inv_out_voltage_tag 17
#define PdDelta_Message_Params_ac_in_freq_tag    18
#define PdDelta_Message_Params_ac_in_voltage_tag 19
#define PdDelta_Message_Params_beep_state_tag    20
#define PdDelta_Message_Params_usb_out_state_tag 21
#define PdDelta_Message_Params_type_c_out_state_tag 22
#define PdDelta_Message_Params_xt60_out_state_tag 23
#define PdDelta_Message_Params_chg_limit_tag     24
#define PdDelta_Message_Params_chg_type_tag      25
#define PdDelta_Message_Params_dsg_limit_tag     26
#define PdDelta_Message_Params_fan_state_tag     27
#define PdDelta_Message_Params_in_type_tag       28
#define PdDelta_Message_Params_err_code_tag      29
#define PdDelta_Message_params_tag               1
#define PdDelta_message_tag                      1

/* Struct field encoding specification for nanopb */
#define PdDelta_FIELDLIST(X, a) \
X(a, STATIC,   OPTIONAL, MESSAGE,  message,           1)
#define PdDelta_CALLBACK NULL
#define PdDelta_DEFAULT NULL
#define PdDelta_message_MSGTYPE PdDelta_Message

#define PdDelta_Message_FIELDLIST(X, a) \
X(a, STATIC,   OPTIONAL, MESSAGE,  params,            1)
#define PdDelta_Message_CALLBACK NULL
#define PdDelta_Message_DEFAULT NULL
#define PdDelta_Message_params_MSGTYPE PdDelta_Message_Params

#define PdDelta_Message_Params_FIELDLIST(X, a) \
X(a, STATIC,   SINGULAR, UINT32,   xt60_in_watts,     1) \
X(a, STATIC,   SINGULAR, UINT32,   xt60_out_watts,    2) \
X(a, STATIC,   SINGULAR, UINT32,   car_out_watts,     3) \
X(a, STATIC,   SINGULAR, UINT32,   ac_in_watts,       4) \
X(a, STATIC,   SINGULAR, UINT32,   inv_out_watts,     5) \
X(a, STATIC,   SINGULAR, UINT32,   pd_out_watts,      6) \
X(a, STATIC,   SINGULAR, UINT32,   usb_qc_out_watts,   7) \
X(a, STATIC,   SINGULAR, UINT32,   type_c_out_watts,   8) \
X(a, STATIC,   SINGULAR, UINT32,   dc_in_watts,       9) \
X(a, STATIC,   SINGULAR, UINT32,   dsg_remain,       10) \
X(a, STATIC,   SINGULAR, UINT32,   chg_remain,       11) \
X(a, STATIC,   SINGULAR, UINT32,   soc,              12) \
X(a, STATIC,   SINGULAR, UINT32,   ac_out_state,     13) \
X(a, STATIC,   SINGULAR, UINT32,   car_out_state,    14) \
X(a, STATIC,   SINGULAR, UINT32,   inv_out_freq,     15) \
X(a, STATIC,   SINGULAR, UINT32,   car_out_voltage,  16) \
X(a, STATIC,   SINGULAR, UINT32,   inv_out_voltage,  17) \
X(a, STATIC,   SINGULAR, UINT32,   ac_in_freq,       18) \
X(a, STATIC,   SINGULAR, UINT32,   ac_in_voltage,    19) \
X(a, STATIC,   SINGULAR, BOOL,     beep_state,       20) \
X(a, STATIC,   SINGULAR, UINT32,   usb_out_state,    21) \
X(a, STATIC,   SINGULAR, UINT32,   type_c_out_state,  22) \
X(a, STATIC,   SINGULAR, UINT32,   xt60_out_state,   23) \
X(a, STATIC,   SINGULAR, UINT32,   chg_limit,        24) \
X(a, STATIC,   SINGULAR, UINT32,   chg_type,         25) \
X(a, STATIC,   SINGULAR, UINT32,   dsg_limit,        26) \
X(a, STATIC,   SINGULAR, UINT32,   fan_state,        27) \
X(a, STATIC,   SINGULAR, UINT32,   in_type,          28) \
X(a, STATIC,   SINGULAR, UINT32,   err_code,         29)
#define PdDelta_Message_Params_CALLBACK NULL
#define PdDelta_Message_Params_DEFAULT NULL

extern const pb_msgdesc_t PdDelta_msg;
extern const pb_msgdesc_t PdDelta_Message_msg;
extern const pb_msgdesc_t PdDelta_Message_Params_msg;

/* Defines for backwards compatibility with code written before nanopb-0.4.0 */
#define PdDelta_fields &PdDelta_msg
#define PdDelta_Message_fields &PdDelta_Message_msg
#define PdDelta_Message_Params_fields &PdDelta_Message_Params_msg

/* Maximum encoded size of messages (where known) */
#define PROTO_PD_DELTA_PB_H_MAX_SIZE             PdDelta_size
#define PdDelta_Message_Params_size              184
#define PdDelta_Message_size                     187
#define PdDelta_size                             190

#ifdef __cplusplus
} /* extern "C" */
#endif

#endif
