[env:disco_h735ig]
platform = ststm32
board = disco_h735ig
framework = stm32cube
build_flags =
    -mfpu=fpv5-d16
    -D HSE_VALUE=25000000UL
board_build.ldscript = stm32h735igkx_flash.ld
extra_scripts = extra_script.py
