/* Automatically generated nanopb constant definitions */
/* Generated by nanopb-0.4.9.1 */

#include "pd335_sys.pb.h"
#if PB_PROTO_HEADER_VERSION != 40
#error Regenerate this file with the current version of nanopb generator.
#endif

PB_BIND(pd335_sys_EventPush, pd335_sys_EventPush, AUTO)


PB_BIND(pd335_sys_EventPush_LogItem, pd335_sys_EventPush_LogItem, AUTO)


PB_BIND(pd335_sys_EventAck, pd335_sys_EventAck, AUTO)


PB_BIND(pd335_sys_ReqTouStrategy, pd335_sys_ReqTouStrategy, AUTO)


PB_BIND(pd335_sys_CfgBeep, pd335_sys_CfgBeep, AUTO)


PB_BIND(pd335_sys_CfgAcOutAlwaysOn, pd335_sys_CfgAcOutAlwaysOn, AUTO)


PB_BIND(pd335_sys_CfgBmsPowerOffWriteAck, pd335_sys_CfgBmsPowerOffWriteAck, AUTO)


PB_BIND(pd335_sys_CfgBmsPushWrite, pd335_sys_CfgBmsPushWrite, AUTO)


PB_BIND(pd335_sys_CfgBmsPushWriteAck, pd335_sys_CfgBmsPushWriteAck, AUTO)


PB_BIND(pd335_sys_SetTimeTaskWrite, pd335_sys_SetTimeTaskWrite, AUTO)


PB_BIND(pd335_sys_SetTimeTaskWriteAck, pd335_sys_SetTimeTaskWriteAck, AUTO)


PB_BIND(pd335_sys_GetAllTimeTaskReadck, pd335_sys_GetAllTimeTaskReadck, AUTO)


PB_BIND(pd335_sys_CfgEnergyBackup, pd335_sys_CfgEnergyBackup, AUTO)


PB_BIND(pd335_sys_CfgTouStrategy, pd335_sys_CfgTouStrategy, AUTO)


PB_BIND(pd335_sys_CfgStormPattern, pd335_sys_CfgStormPattern, AUTO)


PB_BIND(pd335_sys_CfgGeneratorMpptHybridMode, pd335_sys_CfgGeneratorMpptHybridMode, AUTO)


PB_BIND(pd335_sys_CfgGeneratorCareMode, pd335_sys_CfgGeneratorCareMode, AUTO)


PB_BIND(pd335_sys_CfgEnergyStrategyOperateMode, pd335_sys_CfgEnergyStrategyOperateMode, AUTO)


PB_BIND(pd335_sys_ResvInfo, pd335_sys_ResvInfo, AUTO)


PB_BIND(pd335_sys_PropertyUploadPeriod, pd335_sys_PropertyUploadPeriod, AUTO)


PB_BIND(pd335_sys_PvDcChgSetting, pd335_sys_PvDcChgSetting, AUTO)


PB_BIND(pd335_sys_PvDcChgSettingList, pd335_sys_PvDcChgSettingList, AUTO)


PB_BIND(pd335_sys_PvChgMaxItem, pd335_sys_PvChgMaxItem, AUTO)


PB_BIND(pd335_sys_PvChgMaxList, pd335_sys_PvChgMaxList, AUTO)


PB_BIND(pd335_sys_WirelessCoordinateList, pd335_sys_WirelessCoordinateList, AUTO)


PB_BIND(pd335_sys_ConfigWrite, pd335_sys_ConfigWrite, 2)


PB_BIND(pd335_sys_ConfigWriteAck, pd335_sys_ConfigWriteAck, 2)


PB_BIND(pd335_sys_ConfigRead, pd335_sys_ConfigRead, AUTO)


PB_BIND(pd335_sys_ConfigReadAck, pd335_sys_ConfigReadAck, AUTO)


PB_BIND(pd335_sys_DisplayPropertyUpload, pd335_sys_DisplayPropertyUpload, 2)


PB_BIND(pd335_sys_RuntimePropertyUpload, pd335_sys_RuntimePropertyUpload, 2)


PB_BIND(pd335_sys_DevRequest, pd335_sys_DevRequest, AUTO)


PB_BIND(pd335_sys_DevRequestAck, pd335_sys_DevRequestAck, AUTO)
