import freetype
import sys
import os

# Configuration
FONT_PATH = "EcoflowSTM32F4/fonts/materialdesignicons-webfont.ttf"
OUTPUT_PATH_C = "EcoflowSTM32F4/src/ui/font_mdi.c"
OUTPUT_PATH_H = "EcoflowSTM32F4/src/ui/font_mdi.h"
FONT_SIZE = 32  # Pixel size
FONT_NAME = "font_mdi"

# Icons Mapping
ICONS_INPUT = {
    "battery_100": 0xF0079,
    "battery_50": 0xF0079,
    "flash": 0xF01E4,
    "plug": 0xF0425,
    "solar": 0xF059F,
    "usb": 0xF050F,
    "power": 0xF042D,
    "check": 0xF012C,
    "close": 0xF0156,
    "wave": 0xF0588,
    "home": 0xF02DC,
    "cog": 0xF0493,
}

MAPPED_ICONS = {}
START_CODE = 0xF000

for i, (name, input_code) in enumerate(ICONS_INPUT.items()):
    MAPPED_ICONS[name] = {
        "input": input_code,
        "output": START_CODE + i
    }

def generate_font():
    if not os.path.exists(FONT_PATH):
        print(f"Error: Font file not found at {FONT_PATH}")
        return

    face = freetype.Face(FONT_PATH)
    face.set_pixel_sizes(0, FONT_SIZE)

    c_content = f"""#include "lvgl.h"

/*
 * Font: {FONT_NAME}
 * Size: {FONT_SIZE} px
 * Bpp: 1
 * Generated by script. Mapped to PUA 0xF000+
 * CMap Type: FORMAT0_TINY (Continuous Range)
 */

"""

    bitmaps = []
    glyph_dsc = []
    current_bitmap_offset = 0
    unicode_list = []

    sorted_names = sorted(MAPPED_ICONS.keys(), key=lambda k: MAPPED_ICONS[k]["output"])

    for name in sorted_names:
        item = MAPPED_ICONS[name]
        input_code = item["input"]
        output_code = item["output"]

        unicode_list.append(output_code)

        # Force Monochrome Load
        try:
            face.load_char(input_code, freetype.FT_LOAD_RENDER | freetype.FT_LOAD_MONOCHROME | freetype.FT_LOAD_TARGET_MONO)
        except Exception as e:
            print(f"Error loading char {name} (0x{input_code:X}): {e}")
            pass

        bitmap = face.glyph.bitmap
        width = bitmap.width
        rows = bitmap.rows
        pitch = bitmap.pitch
        buffer = bitmap.buffer

        print(f"Glyph {name}: Width={width}, Rows={rows}, Pitch={pitch}")

        # Extract bits
        char_bitmap_bytes = []
        for i in range(rows):
            target_bytes = (width + 7) // 8
            for j in range(target_bytes):
                # For 1bpp, FreeType pitch is bytes per row.
                # buffer is flat.
                if j < abs(pitch):
                    # Handle negative pitch (top-down vs bottom-up)
                    # For bitmaps, usually top-down (positive).
                    idx = i * pitch + j
                    if idx < len(buffer):
                        char_bitmap_bytes.append(buffer[idx])
                    else:
                        char_bitmap_bytes.append(0)
                else:
                    char_bitmap_bytes.append(0)

        bitmaps.extend(char_bitmap_bytes)

        adv_w = face.glyph.advance.x >> 6
        ofs_x = face.glyph.bitmap_left
        ofs_y = face.glyph.bitmap_top - rows

        glyph_dsc.append(f"    {{.bitmap_index = {current_bitmap_offset}, .adv_w = {adv_w}, .box_w = {width}, .box_h = {rows}, .ofs_x = {ofs_x}, .ofs_y = {ofs_y}}}")
        current_bitmap_offset += len(char_bitmap_bytes)

    # Write Bitmap Array
    c_content += "static const uint8_t glyph_bitmap[] = {\n"
    for i in range(0, len(bitmaps), 12):
        chunk = bitmaps[i:i+12]
        c_content += "    " + ", ".join([f"0x{b:02X}" for b in chunk]) + ",\n"
    c_content += "};\n\n"

    # Write Glyph DSC
    c_content += "static const lv_font_fmt_txt_glyph_dsc_t glyph_dsc[] = {\n"
    c_content += ",\n".join(glyph_dsc)
    c_content += "\n};\n\n"

    # Write CMap
    c_content += """
static const lv_font_fmt_txt_cmap_t cmaps[] = {
    {
        .range_start = """ + f"0x{START_CODE:X}" + """, .range_length = """ + str(len(unicode_list)) + """, .glyph_id_start = 0,
        .unicode_list = NULL, .glyph_id_ofs_list = NULL, .list_length = 0, .type = LV_FONT_FMT_TXT_CMAP_FORMAT0_TINY
    }
};

"""

    c_content += f"""
static const lv_font_fmt_txt_dsc_t font_dsc = {{
    .glyph_bitmap = glyph_bitmap,
    .glyph_dsc = glyph_dsc,
    .cmaps = cmaps,
    .kern_dsc = NULL,
    .kern_scale = 0,
    .cmap_num = 1,
    .bpp = 1,
    .kern_classes = 0,
    .bitmap_format = 0
}};

const lv_font_t {FONT_NAME} = {{
    .get_glyph_dsc = lv_font_get_glyph_dsc_fmt_txt,
    .get_glyph_bitmap = lv_font_get_bitmap_fmt_txt,
    .line_height = {FONT_SIZE},
    .base_line = 0,
    .dsc = &font_dsc
}};
"""

    with open(OUTPUT_PATH_C, "w") as f:
        f.write(c_content)

    # Header is static, no change needed (assumed correct from previous step)

    print(f"Generated {OUTPUT_PATH_C}")

if __name__ == "__main__":
    generate_font()
