[env:disco_h735ig]
platform = ststm32
board = disco_h735ig
framework = stm32cube
lib_deps =
    https://github.com/BOJIT/PlatformIO-FreeRTOS.git
    lvgl/lvgl @ ^8.3.11
build_flags =
    -mfpu=fpv5-d16
    -D DATA_IN_ExtSDRAM
    -D HSE_VALUE=25000000UL
    -D LV_CONF_INCLUDE_SIMPLE
board_build.ldscript = stm32h735igkx_flash.ld
board_upload.offset_address = 0x08020000
extra_scripts =
    extra_script.py
    merge_firmware.py
